Step3 - 지뢰 찾기 (게임 실행) 리뷰요청 드립니다.
next-step/kotlin-minesweeper pull request #133
Opened 2022-06-22 14:58 UTC by sah3122

안녕하세요 태현님 😄 

이전 미션에서의 피드백 반영하였고 3번째 미션 리뷰 요청 드립니다.
점점 미션이 끝나가는게 너무 아쉽네요 😢 

이전 미션과 동일하게 TDD 사이클을 지키려고 노력해보았습니다. 
이번 미션도 잘 부탁드립니다 😄

2022-06-24 15:11 UTC, galcyurio requested changes
3단계 미션 고생하셨습니다 👍 
몇 가지 코멘트를 남겨두었으니 확인 후 다시 요청해주세요!

2022-06-24 15:11 UTC, galcyurio commented on src/main/kotlin/minesweeper/domain/MineField.kt
> +        get() = fields.values.filterIsInstance<NonMine>().all { it.isOpen }
내부 `fields`를 외부에서 참조해서 사용하는대신 도메인 로직을 내부에서 처리 👍

2022-06-24 15:11 UTC, galcyurio commented on src/main/kotlin/minesweeper/domain/MineField.kt
>      val fields: Map<Coordinate, Dot>
외부에서 fields를 사용해야하는 경우도 있어서 공개해두신 것 같네요.
개인적으로는 `fields`를 항상 private으로 두고 외부에서 필요한 경우에는 `fun toMap(): Map<Coordinate, Dot>`와 같은 별도의 함수로 분리하고 방어적 복사를 한 다음 넘겨주는 방식을 선호합니다.

이렇게 하는 이유는 fields의 구현체가 MutableMap일 수도 있기 때문에 외부에서 공격하려하면 캐스팅해서 공격할 수 있기 때문이에요.

```kotlin
class MineField {
    fun toMap(): Map<Coordinate, Dot> { ... }
}
```

-----

별개로 생성자로 MutableMap을 넣고 외부에서 내부의 fields를 조작하는 방식으로 공격할 수도 있습니다.
지금 작성해주신 코드는 `return MineField(fields.toMap())`에서 방어적 복사를 해주고 계셔서 중간에 side effect가 끊기기 때문에 안전합니다.

2022-06-25 12:23 UTC, sah3122 commented on src/main/kotlin/minesweeper/domain/MineField.kt
> +    private tailrec fun openAroundCoordinate(coordinate: Coordinate): Unit =
tailrec 키워드에 대해 잘못알고 있었네요. 
제거해두겠습니다 😄

2022-06-26 12:28 UTC, galcyurio approved these changes
피드백 잘 반영해주셨네요 👍 
마지막 단계에서는 모든 코드를 지우고 다시 한 번 철저하게 TDD로 진행해보시거나 또는 이대로 마무리하셔도 좋습니다.

2022-06-26 12:28 UTC, merged