Step4 - 지뢰 찾기(리팩터링)
next-step/kotlin-minesweeper pull request #162
Opened 2022-06-30 12:02 UTC by devwithpug

형준님 안녕하세요 👋
벌써 마지막 단계입니다!

이번 단계에서는 간단한 리팩터링을 몇 가지 진행해 보았어요. 이와 관련해서 형준님은 어떻게 생각하시는지 궁금합니다!

- - -

1. 지뢰 찾기 미션을 진행하면서 랜덤 지뢰 요구사항을 위해 MineMaker 인터페이스를 구현한 RandomMineMaker 를 사용해서 Mine을 생성하고 있었는데요. MineMaker 사용을 강제하다 보니, Empty와 Mine을 생성하는 단계가 각각 분리되어 진행되고 있었어요.
이러한 구조가 신경 쓰여서 MineMaker, RandomMineMaker를 과감히 제거하고 CellMaker object class를 추가해서 Empty와 Mine을 한꺼번에 생성하는 방향으로 리팩터링 해보았어요.

2. 기존 코드에서는 sealed class 인 Cell 을 상속받는 Empty, Mine 클래스가 각각의 파일로 분리되어 있었는데요. sealed class의 특성을 제대로 적용하려면 같은 파일 내에 있어야 한다는 점을 알게 되었습니다.(같은 파일 내에 있지 않으면 when 절에서 else 키워드가 없으면 컴파일 에러 발생)
따라서 Cell의 inner class로 Empty, Mine을 구성해 보았는데요. Cell 클래스는 추가적으로 state 필드와 open(), isClosed(), isOpen() 함수를 가지고 있는데, 이런 구조로도 괜찮을지, 의견 부탁드립니다.

3. 마지막으로는 현재 코드에서는 CellMaker, NearbyMineCounter와 같은 유틸성 object 클래스가 존재하고 있는데요. 도메인 패키지 내부에 이러한 유틸성 object 클래스들을 함께 관리하는 것이 좋을지(?) 아니면.. util 패키지로 분리할지(?) 또는 object 클래스 내부 로직을 도메인의 관심사로 이동해 주는 게 좋을지(?) 에 대해서 의견 부탁드립니다~!

- - -

모든 경우에 대해 정답은 없겠지만, 형준님의 의견이 궁금합니다 😊
마지막 단계 리뷰도 잘 부탁드리겠습니다 🙏

2022-06-30 16:11 UTC, Flamme1004K requested changes
안녕하세요!

와우! 4단계 미션 리팩터링 아주 잘 해주셨습니다! 💯💯💯💯💯💯

질문에 대한 답변 코멘트로 남겼으니, 확인 부탁드리겠습니다!

2022-06-30 16:11 UTC, Flamme1004K commented on src/main/kotlin/minesweeper/domain/cell/CellMaker.kt
> +object CellMaker {
3번째 질문에 대해서는 첫번째와 세번째에서 선택을 할 것 같아요! 😊

첫번째 선택 이유 : CellMaker나, NearbyMineCounter object class는 cell과 board 도메인에 특화된 클래스라고 생각하기 때문에 도메인 클래스에 있는 게 자연스럽다고 생각하고 있어요. 

ps. 앗 여기서 NearbyMineCounte는 board 도메인에 있는 이유를 알 수 있을까요?

세 번째 선택 이유 : object 클래스 내부 로직을 도메인의 관심사로 이동해 주는 게 좋을지(?)에 대해서는 클래스 간의 결합도 한번 생각해 봐야 된다고 생각해요. 만약 합치게 된다면, NearbyMineCounter의 경우에는 Cells와 통합 할 수 있어보여요. 그리고 CellMaker에는 현재 랜덤 로직이 있기 때문에, 랜덤 로직에 대해서는 테스트와 변경에 대해 용이하게 만들기 위하여 DIP를 해줘야하지 않을까하네요. 🤔

준규님 의견도 듣고 싶어요! 🤩

2022-07-01 08:37 UTC, devwithpug commented on src/main/kotlin/minesweeper/domain/cell/Cells.kt
> +            val cells = CellMaker.make(width, height, numberOfMines)
오오 꿀팁 감사합니다!!
코틀린은 디폴트 파라미터를 선언할 수 있는게 너무 좋은 것 같아요 ㅎㅎ
특수한 케이스에서는 파라미터의 구조를 더 유연하게 가져갈 수 있겠네요 👍

2022-07-01 08:38 UTC, devwithpug commented on src/main/kotlin/minesweeper/domain/cell/Cell.kt
> +    class Empty(position: Position, numberOfNearbyMines: Int = 0) : Cell(position) {
답변 감사합니다!!
sealed class 와 이를 상속받는 클래스들이 한 파일 내에만 존재한다면 어떤 구조든지 OK네요! 😊

2022-07-01 09:08 UTC, devwithpug commented on src/main/kotlin/minesweeper/domain/cell/CellMaker.kt
> +object CellMaker {
자세한 답변 감사합니다!! 👍

먼저, NearbyMineCounter가 board 패키지에 있는 이유는 NearbyMineCounter를 처음 만들 때 MineBoard 내부에서 사용하다보니 board 패키지에 선언했었는데요~ 리팩터링을 거치면서 패키지를 옮기는 것을 깜박했네요 😅

음 이 부분은 계속 고민중인데요~ 

첫 번째로, CellMaker의 경우 아래와 같이 전략패턴을 다시 꺼내왔습니다 ㅎㅎ
```kotlin
interface CellMaker {
    fun make(width: Int, height: Int, numberOfMines: Int): List<Cell>
}

object RandomCellMaker : CellMaker {
    override fun make(width: Int, height: Int, numberOfMines: Int): List<Cell> {
        // ...
    }
}
```

또한, 제 생각에는 CellMaker 의 로직이 셀들을 생성하는 큰 로직을 담당하기 때문에 Cells 내부 관심사로 옮기기 보다는, 기존 구조를 유지하는 것도 괜찮다고 생각이 들었습니다.

두 번째로, NearbyMineCounter의 경우는..

처음에는 Cells 내부 로직으로 옮겨도 될 정도의 작은 책임이라고 생각했는데요, Cells 내부 로직으로 옮기려고 하니, NearbyMineCounterTest 클래스가 마음에 걸리더라구요. 

개인적으로 계속 고민을 해보니, NearbyMineCounter.count() 함수는 단위 테스트가 수행되어야 하는 정도의 책임이라는 생각이 들었습니다. 만약 이 함수를 Cells 내부로 옮기게 되면 private 접근제어자를 가지게되고, count() 함수만을 테스트할 수 없게 되더라구요.

따라서, count() 함수가 테스트를 수행하야 하는 정도의 책임을 가지고 있기 때문에 현재로써는 Cells 외부 클래스로 따로 관리하는게 맞다는 생각입니다.. (결국 유틸성 object 클래스를 모두 유지하는 방향이 되었네요 ㅎㅎ;;)

결론은.. 기준 구조와 같이, 첫번째 방법을 선택하려고 합니다!! 😊

2022-07-01 11:07 UTC, Flamme1004K approved these changes
안녕하세요! 

이만 미션 종료하도록 하겠습니다! 

그동안 지뢰찾기 미션 진행하시느라 고생하셨습니다! 🤩

미션 완료 축하드립니다! 🥳🥳

2022-07-01 11:07 UTC, merged