[Step1] 지뢰 찾기(그리기)
next-step/kotlin-minesweeper pull request #192
Opened 2022-12-18 15:17 UTC by SangHyunGil

안녕하세요 리뷰어님!
이번에 처음으로 지뢰 찾기를 구현해보았어요~
이번에 많이 배워가도록 하겠습니다~
리뷰 잘부탁드려요 ㅎㅎ

2022-12-19 13:45 UTC, ddaaac requested changes
안녕하세요 상현님 👋 

코틀린의 다양한 기능들을 적극적으로 활용한 코드들이 인상적이었습니다 👍 

몇 가지 코멘트를 남겼으니 확인 부탁드려요~

2022-12-19 13:45 UTC, ddaaac commented on src/main/kotlin/domain/Field.kt
> +    abstract val type: FieldType
coordinate은 생성자 프로퍼티로, type은 abstract 프로퍼티로 정의해주신 이유가 있을까요?

2022-12-19 13:45 UTC, ddaaac commented on src/main/kotlin/domain/FieldType.kt
> +}
Field가 sealed class이기 때문에 FieldType을 따로 정의하지 않아도 될 것 같아요.
[sealed class vs enum](https://www.baeldung.com/kotlin/sealed-class-vs-enum#sealed-class-vs-enum)에 대한 글을 한 번 읽어보는 것도 좋을 것 같습니다 :)

2022-12-19 13:45 UTC, ddaaac commented on src/main/kotlin/domain/Field.kt
> +    }
toString이 특정(콘솔) View에 지나치게 의존하고 있는 것 같아요. C또는 *로 표시하는 것은 콘솔 View의 규칙이라는 생각이 들어요. 만약 콘솔 View 가 아닌 웹 View로 변경되어서 각 Field를 나타내는데 이미지 파일을 사용하게 된다면 지금의 toString, C, * 가 의미가 있을까요?

2022-12-19 13:45 UTC, ddaaac commented on src/main/kotlin/domain/strategy/RandomMineBoardGenerateStrategy.kt
> +        }.toMap()
```suggestion
        return List(maxCoordinateSize) { number ->
            val coordinate = Coordinate(number)
            when (coordinate in mineCoordinate) {
                true -> Mine(coordinate, FieldType.MINE)
                false -> Land(coordinate, FieldType.LAND)
            }
        }.associateBy { it.coordinate }
```

- 위와 같이 구현할 수도 있어요!
- Fields에서도 key값으로 coordinate를 관리하고, 내부 Field에서도 coordinate을 관리해주는 이유가 있을까요? 같은 데이터를 여러 객체에서 관리하면 동기화에 대한 관리도 해줘야할 것 같아서요.

2022-12-19 13:45 UTC, ddaaac commented on src/main/kotlin/domain/Coordinate.kt
> +)
지뢰찾기에서의 좌표라고 하면 (n, m)과 같이 row/col 쌍으로 구성해보는 건 어떨까요?

2022-12-19 13:45 UTC, ddaaac commented on src/main/kotlin/view/OutputView.kt
> +            println()
print를 위해서 List를 생성할 필요는 없어보여요.
`IntRange`와 `forEach` 등을 사용해보는 건 어떨까요?

2022-12-19 13:45 UTC, ddaaac commented on src/test/kotlin/domain/BoardTest.kt
> +            Then("정상적으로 조회한다.") {
given-when-then을 kotest를 사용해서 효과적으로 나타내주셨네요 👍 

when 이전에 개행이 하나 있으면 조금 더 분명하게 구분할 수 있을 것 같습니다 :)

2022-12-19 13:45 UTC, ddaaac commented on src/main/kotlin/domain/Board.kt
> +    val fields: Fields = strategy.generate(height.value * width.value, mineCnt)
현재 요구사항에서 Board와 Fields가 나뉘어져있지 않아도 될 것 같다는 생각이 드네요. Board에서 직접 Map<Coord, Field>를 관리해도 될 것 같다는 생각이 들어요. 상현님 생각은 어떠신가요?

2022-12-20 15:10 UTC, SangHyunGil commented on src/main/kotlin/domain/Field.kt
> +    abstract val type: FieldType
FieldType은 부모의 타입을 받는 것이 아니라 각 클래스에서 정의해서 사용할 수 있도록 하려고 했어요.
하지만, 아래 코멘트에 남겨주신 것처럼 이미 sealed class로 충분히 표현이 가능해 제거하도록 할게요!

2022-12-20 15:18 UTC, SangHyunGil commented on src/main/kotlin/domain/strategy/RandomMineBoardGenerateStrategy.kt
> +        }.toMap()
동기화 관리 측면에서 Coordinate를 키로만 관리하고 벨류로 가져가는게 더욱 좋겠네요 👍

2022-12-21 13:52 UTC, ddaaac approved these changes
안녕하세요 상현님 👋 

리뷰 반영 잘 해주셨어요~

다음 단계 진행해주세요!

2022-12-21 13:52 UTC, ddaaac commented on src/main/kotlin/domain/strategy/RandomMineBoardGenerateStrategy.kt
> +        return map
```suggestion
        return (0..height.value).flatMap { h ->
            (0..width.value).map { w ->
                val coordinate = Coordinate(h, w)
                val field = when (coordinate in mineCoordinate) {
                    true -> Mine()
                    false -> Land()
                }
                coordinate to field
            }
        }.toMap()
```
이런 식으로도 작성할 수 있습니다. height, width에 대한 계산이 없어서 더 읽기 간단하다고 느껴지는데 상현님의 생각은 어떠신가요?

2022-12-21 13:52 UTC, ddaaac commented on src/test/kotlin/domain/FieldsTest.kt
> +                field::class shouldBe Land::class
`field is Land`로도 나타낼 수 있어요 😄

2022-12-21 13:52 UTC, merged