[Step1] 지뢰 찾기(그리기)
next-step/kotlin-minesweeper pull request #195
Opened 2022-12-20 14:54 UTC by namonak

2022-12-20 14:59 UTC, namonak commented
김수현(@wisemuji) 리뷰어님,

많이 늦었지만 첫 PR 요청을 드립니다! 독려해 주신 덕분에 그나마 첫 단계를 시작 할 수 있었어요 😃
혹독한 리뷰 부탁드리겠습니다 🙏

2022-12-22 02:51 UTC, wisemuji requested changes
안녕하세요 최정님!

구현을 잘 해주셨습니다 💯  깔끔한 구현이 좋았습니다. 
고민해보시면 좋을만한 코멘트를 달았으니 확인해주시면 감사하겠습니다.
이번 단계에서는 랜덤 로직을 테스트에서 제외하는 것과 좌표값을 의미있는 클래스로 나누는 것에 초점을 맞추시면 더욱 좋을 것 같아요.

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 💪

2022-12-22 02:51 UTC, wisemuji commented on src/main/kotlin/minesweeper/controller/InputParser.kt
> +        require(inputNumber.toIntOrNull() != null) { "숫자를 입력해주세요." }
[requireNotNull](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/require-not-null.html)을 활용해보면 어떨까요?

2022-12-22 02:51 UTC, wisemuji commented on src/main/kotlin/minesweeper/domain/Land.kt
> +    fun getTiles(): List<List<String>> {
이 프로그램을 다른 개발자들과 함께 유지보수한다고 생각했을때, `List<List<String>>`을 보고 어떤 값이 width이고 어떤 값이 height인지 인지할 수 있을까요? 어떻게 개선해볼 수 있을까요?

2022-12-22 02:51 UTC, wisemuji commented on src/main/kotlin/minesweeper/domain/generator/TileGenerator.kt
> +}
value class 활용 👍  전략 패턴으로 테스트 가능한 구조 만들기 👍

2022-12-22 02:51 UTC, wisemuji commented on src/main/kotlin/minesweeper/domain/tile/Marking.kt
> +}
만약 UI 요구사항이 바뀌어 지뢰를 `@`로 표기하는 것으로 바뀐다면 어떻게 될까요? UI 로직의 변경사항으로 인해 도메인 로직이 수정되는 상황이 발생하게 됩니다. 도메인 로직이 UI 로직에 의존하지 않도록 의존성을 끊어보면 어떨까요? 이로 인해 구조가 좀 바뀔 수 있을 것 같습니다 🙂

2022-12-22 02:51 UTC, wisemuji commented on src/main/kotlin/minesweeper/domain/tile/Tile.kt
> +}
이번 기회에 Kotlin의 [sealed class/interface](https://kotlinlang.org/docs/sealed-classes.html)에 대해 학습하고 Tile을 구현하는 클래스 관계에 적용해보면 어떨까요~? 일반 클래스로 구현하는 것과 어떤 차이가 있을까요?

2022-12-22 02:51 UTC, wisemuji commented on src/main/kotlin/minesweeper/domain/tile/strategy/RandomGenerateStrategy.kt
> +            tiles.add(mountCount--.let { if (it > 0) Mine(coordinate) else NotChecked(coordinate, false) })
Mine인지 NotChecked인지 여부를 Strategy에서 판단하는 것이 아닌, 메세지만 던져 스스로 판단하게 하면 어떨까요? 위에서 드린 코멘트처럼 sealed class로 구현하면 다음과 같이 인스턴스를 만들기 전에 조건문을 넣어 어떤 타입의 인스턴스를 만들지 스스로 판단하게 만들 수 있습니다.

```kotlin
sealed class State {
    data class Empty(val foo: String): State() 

    data class NotEmpty(val foo: String): State()
 
    companion object {
        fun of(isEmpty: Boolean, foo: String): State {
            return if (isEmpty) Empty(foo) else NotEmpty(foo)
        }
    }   
}
```

2022-12-22 02:51 UTC, wisemuji commented on src/test/kotlin/minesweeper/domain/LandTest.kt
> +        assert(actual == expected)
```suggestion
        assertThat(actual).isEqualTo(expected)
```
assertThat을 활용하는걸 권장드립니다!

참고: https://jongmin92.github.io/2020/03/31/Java/use-assertthat/

2022-12-22 02:51 UTC, wisemuji commented on src/test/kotlin/minesweeper/domain/LandTest.kt
> +    fun `Land - 문자열 타일 목록 반환 테스트`() {
테스트명을 통해 어떤 것을 테스트하고자 하는 것이 제대로 드러나지 않는다고 생각합니다. 테스트명을 작성하실 때에는
1. 검증하고자 하는 로직을 명확하게 정하고 (검증이 필요한 로직이 두 개 이상이면 필요에 따라 또 다른 함수로 분할한다)
2. 그것을 함수명으로 드러내보면 어떨까요?



(이하 동일합니다)

2022-12-22 02:51 UTC, wisemuji commented on src/test/kotlin/minesweeper/domain/LandTest.kt
> +            )
```suggestion
            listOf(
                Mine(Coordinate.of(0, 0)), NotChecked(Coordinate.of(0, 1), false),
                NotChecked(Coordinate.of(1, 0), false), Mine(Coordinate.of(1, 1))
            )
```
List 타입이므로 굳이 ArrayList를 만들지 않아도 될 것 같아요. 🙂

2022-12-22 02:51 UTC, wisemuji commented on src/test/kotlin/minesweeper/domain/generator/TileGeneratorTest.kt
> +        assertThat(FIXED_MINE_COUNT).isEqualTo(tiles.count { it.isMine })
전략 패턴을 사용하셨지만 테스트에서는 여전히 랜덤 로직이 포함되어 있어요. 랜덤 로직을 테스트에서 사용하게 되면 항상 같은 결과를 보장하기 어렵습니다. (지금 assert문에서는 같은 결과를 보장하게 될 것 같지만요)

> 전략 패턴은 프로그램이 진행되면서 캡슐화된 로직을 선택할 수 있게 하는 디자인 패턴입니다. 로직 실행은 인터페이스에 의존을 시키고 인터페이스를 구현한 로직들을 전달해줌으로써 분기처리 없이 유연성을 갖출 수가 있습니다.

GenerateStrategy 인터페이스를 구현하는 또다른 클래스를 만들어 랜덤 로직은 테스트에서 제외될 수 있도록 개선해보면 어떨까요? 관련 예시는 다음 글을 참고해보시는걸 추천드립니다 : https://tecoble.techcourse.co.kr/post/2021-10-04-strategy-command-pattern/

2022-12-23 07:37 UTC, namonak commented on README.md
> +# kotlin-minesweeper
칭찬해 주셔서 감사합니다! 😄

2022-12-26 16:46 UTC, namonak commented on src/test/kotlin/minesweeper/domain/LandTest.kt
> +        assert(actual == expected)
세심한 부분까지 확인해 주셔서 감사합니다 🙏 특히 전달해 주신 참고자료가 많은 도움이 되었습니다! 추후에도 테스트 코드 작성시에 `assertThat`을 활용하겠습니다 😄 아래와 같이 수정 반영하였습니다! 😃 

- https://github.com/next-step/kotlin-minesweeper/commit/1ea3b54b4436131da4b91d186c9115b51efae879

2022-12-26 16:49 UTC, namonak commented on src/main/kotlin/minesweeper/domain/generator/TileGenerator.kt
> +}
칭찬 감사합니다! 😃

2022-12-26 16:57 UTC, namonak commented on src/test/kotlin/minesweeper/domain/LandTest.kt
> +            )
네, 조언해 주신 내용 확인해 보니 굳이 `ArrayList` 사용은 불필요해 보이네요 🥲 제안해 주신 부분 그대로 적용하였습니다! 감사합니다 🙏😄

- https://github.com/next-step/kotlin-minesweeper/commit/4376db1111a01e136635e8a9aa5695da7b8da7da

2022-12-27 03:31 UTC, namonak commented on src/main/kotlin/minesweeper/domain/tile/Tile.kt
> +}
네! 😊 조언해 주신대로 Kotlin의 [sealed class/interface](https://kotlinlang.org/docs/sealed-classes.html)에 대해 학습하고, `Tile` 에 sealed interface를 적용해 보았습니다!

만일 `Tile` 자체에 구현이 필요한 메서드 혹은 프로퍼티가 있었다면 sealed class를 적용했을텐데, 현재 상황에서는 별도로 구현할 메서드나 프로퍼티가 없기에 sealed interface가 적절하다고 판단했습니다 😊

sealed class/interface는 컴파일 타임에 자신을 상속받는 하위 클래스들을 컴파일러에게 알려주기 때문에, sealed class를 상속받는 하위 클래스의 종류를 제한하는 특성이 있네요 😄또한 외부 모듈에서는 sealed class를 확장할 수 없는 특징이 있습니다! (그래서 이름이 sealed class 일까요? 🤔)

그리고 수정을 하면서 확인한 부분인데, sealed class/interface와 이를 상속받는 하위 클래스들은 같은 파일 혹은 같은 패키지 경로에 위치해야 된다는 사실도 확인했습니다. (그래서 `Tile`의 패키지 위치를 `minesweeper.domain.tile` 에서 `minesweeper.domain.tile.state`로 변경했습니다!)

위와 같은 특징들을 고려해 볼때, 상태 구분이 명확한 로직을 구현할때, sealed class/interface를 사용하는 것이 용이할 것으로 생각됩니다! 

예를들어, 
- sealed class/interface를 사용하지 않은 채로 추가적인 상태값이 추가된다고 가정 했을때, `when`을 통해 상태값을 핸들링 하는 경우, 개발자 실수로 추가적인 상태값에 대한 핸들링 코드를 추가하지 않더라도 컴파일러는 그냥 넘어갈 것입니다. 그리고 이는 찾아내기 어려운 버그 일것으로 예상됩니다!
- 그러나, sealed class/interface를 사용하는 경우, 컴파일러에서 sealed class/interface를 상속받는 하위 클래스들을 알기에 컴파일 타임에 에러를 출력하고 컴파일이 되지 않기에, 버그를 미연에 방지할 수 있을것으로 생각됩니다 😊

제가 제대로 이해한 것인지 확인을 부탁드리겠습니다 🙏

- https://github.com/next-step/kotlin-minesweeper/commit/1cc4720e7d6865089481d307aadc7f64f23d3885

2022-12-27 04:35 UTC, namonak commented on src/main/kotlin/minesweeper/domain/Land.kt
> +    fun getTiles(): List<List<String>> {
조언해 주신 부분에 대해서 다양하게 고민해 봤는데요! 😊

`List<List<String>>`를 사용하기 보다는 `List<String>`에 `width` 파라미터를 조합하여 최종 결과를 출력하는 것이 낫다고 판단했습니다!
이렇게 하니 `Land` 객체와 `ResultView` 객체의 코드도 상당히 간결해지는 효과를 추가로 보았는데요! 😄

리뷰어님 의도를 제가 제대로 파악한 것인지 확인 부탁드리겠습니다 🙏 

- https://github.com/next-step/kotlin-minesweeper/commit/c9752b8406e93e28dc868d7810f74e172174fb61

2022-12-27 05:10 UTC, namonak commented on src/main/kotlin/minesweeper/domain/tile/Marking.kt
> +}
Domain 영역과 UI 영역을 분리하는 가장 기본적인 원칙을 지키지 못했네요 😭 이 부분 확인해 주셔서 감사합니다 🙏 

먼저, `Marking` enum class 에서 `symbol` 프로퍼티를 삭제하였고, `LandDto` 객체를 추가하였습니다.
그리고, `LandDto` 객체에서 UI 영역으로 전달되는 지뢰 표기에 대한 문자값을 치환(`getMarkingAsString()`)하여 전달하도록 해보았습니다! 확인을 부탁드리겠습니다 🙏🙇

2022-12-27 06:23 UTC, namonak commented on README.md
> +# kotlin-minesweeper
[requireNotNull](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/require-not-null.html)에 대한 링크 까지 전달해 주셔서 감사합니다 😊 추가로 [check](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/check.html) , [checkNotNull](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/check-not-null.html) 등이 있는 것도 확인하였습니다!

다만, 짚어 주신 부분 관련하여 추가로 테스트를 진행해 보니, `require` 보다는 아래와 같이 처리하는 것이 원래 제 의도대로 동작하는 터라 다음과 같이 수정해 보았습니다.

```kotlin
return inputNumber.toIntOrNull() ?: throw IllegalArgumentException("숫자를 입력해주세요.")
```

- https://github.com/next-step/kotlin-minesweeper/commit/05efa4b4a106cf6e9c7b1bfe7b29450f7ed94a63

리뷰어님의 조언을 무시한 것은 아니고, 기존 제 구현이 잘못되어 수정한 것이니 너른 양해를 부탁드리겠습니다 🙏🙇😭 
알려주신 방법은 추후에 도전과제를 진행하면서 꼭 활용해 보도록 하겠습니다! 😀 (i.e. 3단계 - 지뢰 찾기(게임 실행)에서의 좌표 입력 등)

2022-12-27 07:07 UTC, namonak commented on src/main/kotlin/minesweeper/domain/generator/TileGenerator.kt
> +}
오! 알려주신 방법대로 '정적 팩토리 매서드'를 적용하여 조건문에 따라 다른 타입의 인스턴스를 생성하도록 수정하니, 코드가 훨씬 직관적으로 변한것 같습니다!
아래와 같이 수정해 봤습니다! 확인 부탁드려요 🙏

- https://github.com/next-step/kotlin-minesweeper/commit/98f7c65e89fd30a9c51b15d3e9e6fb038e9dbca5

그리고, `NotChecked` 객체의 `isMine` 프로퍼티는 항상 `false`일 수는 없지만 현재 요구사항을 반영하기 위해 일단 `false`로 두고, 추후에 기능 반영하도록 하겠습니다 😊

2022-12-27 13:05 UTC, namonak commented on src/test/kotlin/minesweeper/domain/LandTest.kt
> +    fun `Land - 문자열 타일 목록 반환 테스트`() {
네, 조언해 주신 대로 테스트 코드 대부분을 리팩토링 해보았습니다 😀

`@ ParameterizedTest ` , `@CsvSource` 조합으로 테스트 했던 부분들을 다시 한번 살펴보니, 가독성도 떨어지고 검증 로직 간의 명확한 구분이 되지 않아 `@Test` 어노테이션을 적용하여 두 개로 나누었습니다!
또한, 함수명은 한글로 작성하긴 했지만 최대한 간결하고 명확하게 수정해 보았습니다! 

확인을 부탁드립니다 🙏

- https://github.com/next-step/kotlin-minesweeper/commit/5b7eab5bdcfeb5d55e0bb92ebb092abaa7c44b4d

2022-12-27 13:12 UTC, namonak commented on src/test/kotlin/minesweeper/domain/generator/TileGeneratorTest.kt
> +        assertThat(FIXED_MINE_COUNT).isEqualTo(tiles.count { it.isMine })
넵! 랜덤 로직을 제거하기 위해 지뢰가 가장 먼저 생성되게 끔하는 `MineFirstGenerateStrategy` 생성 전략을 추가해 보았습니다 😃
확인 부탁드립니다 🙏

- https://github.com/next-step/kotlin-minesweeper/commit/f5deb6d0738bd2ab7be5f29c0f40be455e444f8f , https://github.com/next-step/kotlin-minesweeper/commit/46b4b6abaaa78389164e2a21b43c70a18cbafd23

2022-12-27 13:24 UTC, namonak commented on src/main/kotlin/minesweeper/controller/InputParser.kt
> +        require(inputNumber.toIntOrNull() != null) { "숫자를 입력해주세요." }
[requireNotNull](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/require-not-null.html)에 대한 링크 까지 전달해 주셔서 감사합니다 😊 추가로 [check](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/check.html) , [checkNotNull](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/check-not-null.html) 등이 있는 것도 확인하였습니다!

다만, 짚어 주신 부분 관련하여 추가로 테스트를 진행해 보니, `require` 보다는 아래와 같이 처리하는 것이 원래 제 의도대로 동작하는 터라 다음과 같이 수정해 보았습니다.

```kotlin
return inputNumber.toIntOrNull() ?: throw IllegalArgumentException("숫자를 입력해주세요.")
```

- https://github.com/next-step/kotlin-minesweeper/commit/05efa4b4a106cf6e9c7b1bfe7b29450f7ed94a63

리뷰어님의 조언을 무시한 것은 아니고, 기존 제 구현이 잘못되어 수정한 것이니 너른 양해를 부탁드리겠습니다 🙏🙇😭 
알려주신 방법은 추후에 도전과제를 진행하면서 꼭 활용해 보도록 하겠습니다! 😀 (3단계 - 지뢰 찾기에서의 좌표 입력 등)

2022-12-27 13:27 UTC, namonak commented on src/main/kotlin/minesweeper/domain/tile/strategy/RandomGenerateStrategy.kt
> +            tiles.add(mountCount--.let { if (it > 0) Mine(coordinate) else NotChecked(coordinate, false) })
오! 알려주신 방법대로 '정적 팩토리 매서드'를 적용하여 조건문에 따라 다른 타입의 인스턴스를 생성하도록 수정하니, 코드가 훨씬 직관적으로 변한것 같습니다!
아래와 같이 수정해 봤습니다! 확인 부탁드려요 🙏

- https://github.com/next-step/kotlin-minesweeper/commit/98f7c65e89fd30a9c51b15d3e9e6fb038e9dbca5

그리고, `NotChecked` 객체의 `isMine` 프로퍼티는 항상 `false`일 수는 없지만 현재 요구사항을 반영하기 위해 일단 `false`로 두고, 추후에 기능 반영하도록 하겠습니다 😊

2022-12-27 13:33 UTC, namonak commented on src/main/kotlin/minesweeper/domain/tile/Tile.kt
> +}
https://github.com/next-step/kotlin-minesweeper/pull/195#discussion_r1057679144 코멘트로 남겨드린 수정사항을 반영했더니, `Tile` 객체에 sealed class 가 적용되었습니다 😃

2022-12-29 08:53 UTC, wisemuji approved these changes
안녕하세요 최정님! 리뷰 반영을 잘 해주셨습니다 💯 

조금 고민해보시면 좋을 내용을 코멘트로 달았으니 다음 단계 미션 진행해주시면서 같이 반영해주시면 됩니다!
지뢰찾기 미션은 블랙잭에 비해 오래 걸리지 않으니 꼭 함께 완주해봐요 ☺️ 

다음 미션도 화이팅입니다 🙏

2022-12-29 08:53 UTC, wisemuji commented on src/main/kotlin/minesweeper/controller/InputFilter.kt
> +            InputView.printError(e.message!!)
의식적으로 에러 메세지를 적어주지 않으면 예상치 못하게 NullPointerException을 만날 수 있습니다.
저는 개인적으로 코틀린의 null safe한 언어적 특성을 충분히 활용하기 위해 `!!` 연산자를 사용할 때에는 꼭 필요한 상황인지 체크하고 사용하려고 합니다. 🙂

2022-12-29 08:53 UTC, wisemuji commented on src/main/kotlin/minesweeper/domain/tile/pos/Coordinate.kt
> +data class Coordinate(private val posX: Position, private val posY: Position) {
프로그래밍 요구사항에 제시된 다음 객체지향 생활 체조 원칙을 지켜보면 어떨까요?
> 줄여 쓰지 않는다(축약 금지).

2022-12-29 08:53 UTC, wisemuji commented on src/main/kotlin/minesweeper/domain/tile/strategy/RandomGenerateStrategy.kt
> +            tiles.add(mountCount--.let { if (it > 0) Tile.of(coordinate, true) else Tile.of(coordinate, false) })
https://github.com/next-step/kotlin-minesweeper/pull/195#discussion_r1055033093 이 코멘트에 이어서...
다음처럼 Tile에 정말 메세지만 던지는 것을 의도했습니다! 구현은 최대한 객체 내에 감춰두고 외부에서는 메세지만 던져보세요!
```suggestion
            tiles.add(Tile.of(coordinate, mountCount--))
```

2022-12-29 08:53 UTC, wisemuji commented on src/main/kotlin/minesweeper/dto/LandDto.kt
> +    }
도메인이 UI에 의존하지 않도록 변경 👍

2022-12-29 08:53 UTC, merged

2022-12-29 09:11 UTC, namonak commented on src/main/kotlin/minesweeper/dto/LandDto.kt
> +    }
칭찬해 주셔서 감사합니다! 조금 더 힘내 보겠습니다! 항상 감사드려요! 😊

2022-12-29 15:30 UTC, namonak commented on src/main/kotlin/minesweeper/controller/InputFilter.kt
> +            InputView.printError(e.message!!)
네, 코멘트 주신대로 `!!` 연산자를 사용하지 않고, `let` 함수를 사용하는 방법으로 수정해 보았습니다 😊
세세한 부분 까지 봐주셔서 감사합니다! 아래와 같이 수정하였습니다 😊

- https://github.com/next-step/kotlin-minesweeper/commit/d69941a609b597b9c78a60b3dd6eaebcf3d2a303

2022-12-29 15:50 UTC, namonak commented on src/main/kotlin/minesweeper/domain/tile/pos/Coordinate.kt
> +data class Coordinate(private val posX: Position, private val posY: Position) {
기본적인 원칙을 지키지 못했네요 😭 
posX/Y 프로퍼티명을 positionX/Y로 변경해 보았습니다! 확인 부탁드릴게요 🙏 

- https://github.com/next-step/kotlin-minesweeper/commit/a4dd1f63b34710ea8275d6b6d529e1d20af73177

2022-12-29 16:12 UTC, namonak commented on src/main/kotlin/minesweeper/domain/tile/strategy/RandomGenerateStrategy.kt
> +            tiles.add(mountCount--.let { if (it > 0) Tile.of(coordinate, true) else Tile.of(coordinate, false) })
전달해 주신 코멘트 꼭 기억해 두겠습니다! 제가 처음에 너무 복잡하게 생각했네요... 조언해 주신 방법대로 해보니 코드가 훨씬 깔끔해 졌습니다 😊

> 구현은 최대한 객체 내에 감춰두고 외부에서는 메세지만 던져보세요!

- https://github.com/next-step/kotlin-minesweeper/commit/72b041dd0ae8faa26ded77aea40dbd2de8d33d58