1단계 - 지뢰 찾기(그리기)
next-step/kotlin-minesweeper pull request #201
Opened 2022-12-22 08:36 UTC by jpoh281

안녕하세요? 길환님 👋
독서모임에서 뵙다가 여기서 보니까 더 반갑습니다.

피드백 잘 부탁드려요!

2022-12-23 08:18 UTC, ohgillwhan requested changes
종표님 코드 잘 봤습니다! 리뷰 확인 부탁드려요

2022-12-23 08:18 UTC, ohgillwhan commented on src/main/kotlin/minesweeper/domain/MineBlock.kt
> +    override fun toString(): String {
`tostring`도 현재 `view`를 위한것 같네요!

2022-12-23 08:18 UTC, ohgillwhan commented on src/main/kotlin/minesweeper/view/InputView.kt
> +        val userInput: String? = readlnOrNull()
`OrNull`을 안해도 괜찮지 않을까요?

2022-12-23 08:18 UTC, ohgillwhan commented on src/test/kotlin/minesweeper/MineSweeperBoardTest.kt
> +        assertThat(exception.message).isEqualTo("지뢰의 개수는 총 블록의 개수보다 많을 수 없습니다.")
메세지를 비교하는거는 변경에 취약합니다! 이럴 땐 `Custom Exception`을 만들어서 타입을 체크하는것도 좋아요

2022-12-23 08:18 UTC, ohgillwhan commented on src/main/kotlin/minesweeper/controller/GameController.kt
> +class GameController {
`View`를 인터페이스로 만들면 컨트롤러에 대해 테스트도 가능할것 같아요

2022-12-23 08:18 UTC, ohgillwhan commented on src/main/kotlin/minesweeper/domain/MineSweeperBoard.kt
> +    val mineCount
이렇게 다시 정의하는게 아닌, `countMine()`을 사용해도 괜찮지 않을까요?

2022-12-23 08:18 UTC, ohgillwhan commented on src/main/kotlin/minesweeper/domain/MineSweeperBoard.kt
> +    val mineCount
그리고 해당 함수를 사용하는게 아닌 생성자에서 받은 `mineCount`를 변수로 정의해서 사용해도 괜찮지 않을까요?

2022-12-23 08:30 UTC, jpoh281 commented on src/main/kotlin/minesweeper/domain/MineSweeperBoard.kt
> +    val mineCount
원래 지뢰찾기 게임에서 깃발을 사용할 때 지뢰의 수가 점점 줄어드는 걸 표현하려다 보니까  생각이 좀 많아졌던 것 같아요.
backing property를 이용해서 내부에서는 `var`로 관리하고 외부에는 `val`로 보이도록 한 뒤에
호출할 때 마다 계산하는 것이 아닌, 맵에 변경이 생길때 마다 다시 측정하는걸로 변경하면 될 것 같아요!

2022-12-23 08:32 UTC, jpoh281 commented on src/main/kotlin/minesweeper/domain/MineSweeperBoard.kt
> +    private val _state: MutableList<MutableList<Block>>
`mutable`하게 둔 뒤 변경하는 방식과, `copy()`를 통해 변경하는 방법 중 `mutable` 을 선택했는데
`copy()`하면서 변경하는게 더 좋을까요?

2022-12-23 08:33 UTC, jpoh281 commented on src/main/kotlin/minesweeper/domain/MineSweeperBoard.kt
> +        _state = boardState
넵! 이부분은 제가 체크를 잘 못한 것 같네요. 😅

2022-12-23 08:33 UTC, jpoh281 commented on src/main/kotlin/minesweeper/domain/MineSweeperBoard.kt
> +        }.toMutableList()
이 부분은 생각을 못했어요. 감사합니다!

2022-12-23 08:40 UTC, jpoh281 commented on src/main/kotlin/minesweeper/controller/GameController.kt
> +class GameController {
아 `FakeView`를 만들라는 말씀이시죠?

2022-12-27 03:12 UTC, jpoh281 commented
안녕하세요? 길환님!
피드백 반영했어요. 다만 View를 인터페이스로 바꾸는건 했는데 테스트는 어떻게 추가해야할지 감이 잘 안와서... 이 부분은 추가적으로 조언해주실 수 있으실까요?

2022-12-28 00:39 UTC, ohgillwhan approved these changes
종표님 코드 잘 봤습니다
다음 step 부탁드려요!

2022-12-28 00:39 UTC, ohgillwhan commented on src/main/kotlin/minesweeper/controller/GameController.kt
> +    private val resultView: ResultView = ResultViewImpl()
💯

2022-12-28 00:39 UTC, ohgillwhan commented on src/main/kotlin/minesweeper/controller/GameController.kt
> +    fun run(): Map<Point, Block> {
`MineSweeperBoard` 를 반환하는건 어떤가요?

2022-12-28 00:39 UTC, ohgillwhan commented on src/main/kotlin/minesweeper/domain/Block.kt
> +sealed class Block {
`sealed class` 💯

2022-12-28 00:39 UTC, ohgillwhan commented on src/main/kotlin/minesweeper/domain/MineSweeperBoard.kt
> +    }
랜덤에 크게 의존하네요! 이렇게 되면 테스트코드 작성하기가 조금 어려워 지죠!

2022-12-28 00:39 UTC, ohgillwhan commented on src/main/kotlin/minesweeper/domain/MineSweeperBoard.kt
> +        }
`(0 until maxXAxis).flatMap{}` 을 이용해보는건 어떨까요?

2022-12-28 00:39 UTC, ohgillwhan commented on src/main/kotlin/minesweeper/view/ResultViewImpl.kt
> +private const val BLANK = " "
`companion object`에 넣어볼까요?

2022-12-28 00:39 UTC, ohgillwhan commented on src/main/kotlin/minesweeper/domain/ExceptionReason.kt
> +    MINE_COUNT_OVER_BLOCKS("지뢰의 개수는 총 블록의 개수보다 많을 수 없습니다.")
화면에 대한 문자군요!

2022-12-28 00:39 UTC, ohgillwhan commented on src/main/kotlin/minesweeper/controller/GameController.kt
> +class GameController(
이 부분도 테스트가 가능하지 않을까요?

2022-12-28 00:39 UTC, merged