feat: Step1: 지뢰 찾기(그리기)
next-step/kotlin-minesweeper pull request #207
Opened 2022-12-25 07:04 UTC by rolroralra

- [x] 높이와 너비, 지뢰 개수를 입력받을 수 있다.
- [x] 지뢰는 눈에 잘 띄는 것으로 표기한다.
- [x] 지뢰는 가급적 랜덤에 가깝게 배치한다.

2022-12-26 06:54 UTC, malibinYun requested changes
1단계 미션 고생 많으셨어요!
많이 어색하고 어려울 수 있지만, TDD를 연습해보는 것을 추천드려요!
작은 미션부터 차근차근 연습해보신다면 분명 익숙해지실거라 생각이 들어요 :)
그리고 테스트 코드가 부족하네요 🥲
다른 객체들의 유닛 테스트들을 모두 작성해주세요 :)

생각해보면 좋을 점들에 코멘트 남겨두었으니 확인 부탁드릴게요!
피드백 반영하시구 다시 리뷰 요청 부탁드려요~!

2022-12-26 06:54 UTC, malibinYun commented on src/main/kotlin/minesweeper/domain/MineBoard.kt
> +    val buttons: Buttons = Buttons.of(height, width, totalMineCount)
buttons를 생성자 파라미터 및 멤버변수로 가져 보는 것은 어떨까요?
외부로부터 주입받을 수 있는 형태라, buttons를 자유롭게 다룰 수 있는 이점이 생기겠네요 :)

2022-12-26 06:54 UTC, malibinYun commented on src/main/kotlin/minesweeper/domain/button/Button.kt
> +)
sealed class를 활용해주셨네요 👍👍

2022-12-26 06:54 UTC, malibinYun commented on src/main/kotlin/minesweeper/domain/button/Button.kt
> +) : Button(position) {
buttons의 position을 open으로 열어놓고 하위 구현체에서 override하는 것은 필수가 아닙니다.
Mine 등의 하위 구현체에서는 파라미터로만 position을 받고, Button 생성자에 position을 넣어주기만 하면 돼요 :)
물론 하위 구현체에서 position을 접근해서 사용할 수 있어요!

2022-12-26 06:54 UTC, malibinYun commented on src/main/kotlin/minesweeper/domain/button/Button.kt
> +    override val position: Position
`지뢰 아님` 보다는, 더 구체적인 이름을 지어주는 것은 어떨까요?

2022-12-26 06:54 UTC, malibinYun commented on src/main/kotlin/minesweeper/domain/button/Buttons.kt
> +) : List<List<Button>> by buttonGraph {
이미 Button에 position을 가지고 있으니, List의 List를 갖지 않아도 충분해 보여요.
혹은 한 열에 대한 Row 객체를 가지고, 해당 Row객체를 List로 가지는 방법도 있겠네요 :)

2022-12-26 06:54 UTC, malibinYun commented on src/main/kotlin/minesweeper/domain/button/Buttons.kt
> +) : List<List<Button>> by buttonGraph {
또, kotlin delegate (by buttonGraph)를 활용해서 쓰지 않을 List에 대한 API를 노출시키기보다, 필요한 API만을 만들어서 노출시키는 것은 어떨까요?

2022-12-26 06:54 UTC, malibinYun commented on src/main/kotlin/minesweeper/domain/button/Buttons.kt
> +
랜덤의 요소 때문에 테스트가 어려운 코드네요.
강의때 배운 랜덤 테스트에 대해 떠올리면서 랜덤의 요소를 외부로부터 주입 받는 형태로 변경해보는 것은 어떨까요?

2022-12-27 10:31 UTC, rolroralra commented on src/main/kotlin/minesweeper/domain/MineBoard.kt
> +    val buttons: Buttons = Buttons.of(height, width, totalMineCount)
리뷰 감사합니다.

2022-12-27 10:32 UTC, rolroralra commented on src/main/kotlin/minesweeper/domain/button/Button.kt
> +) : Button(position) {
리뷰 감사합니다.

2022-12-27 10:32 UTC, rolroralra commented on src/main/kotlin/minesweeper/domain/button/Button.kt
> +    override val position: Position
넵 네이밍 변경해서 반영하겠습니다. `PushableButton`

2022-12-27 10:39 UTC, rolroralra commented on src/main/kotlin/minesweeper/domain/button/Buttons.kt
> +
아 맞네요. 좋은 리뷰 감사합니다. 반영하겠습니다.

2022-12-28 14:29 UTC, rolroralra commented on src/main/kotlin/minesweeper/domain/button/Buttons.kt
> +) : List<List<Button>> by buttonGraph {
기본적으로 일급컬렉션 객체의 역할을 한다고 가정했을때는,

필요한거만 구현하는거보다, delegate를 통해서 mutableCollection 의 인테페이스를 제공하는것이 좀 편하다고 생각이 듭니다.

List<List<Button>> 의 경우는 리뷰주신대로 좋지않아 보이네요.

코드리뷰 반영하겠습니다.

2022-12-28 15:23 UTC, malibinYun requested changes
피드백 반영 고생 많으셨어요 :)
피드백 내용 이외에도 굉장히 많은 코드들을 작성해주셨는데요,
전반적으로 실제로 사용하지 않아, 필요하지 않은 메서드들이 너무 많이 보였어요 :)
필요한 책임과 역할만을 잘 골라내어서, 적절한 객체에 위임해보는 연습을 이 미션을 통해 해보셨으면 좋겠어요! 😀

또, 전반적인 테스트 로직이 특정 객체가 생성되었는지가 대부분이었어요.
객체 생성할 때 생성이 되어서는 안되는 부분 (ExceptionTest)는 잘 구현해주셨는데요, 다른 메서드들이 잘 동작하는 지 테스트 하는 것도 구현해보시길 바라요 :)
여기서 가장 중요한 테스트는 랜덤한 위치에 지뢰가 잘 배치되는 지 테스트해보는 것이겠는데요, 강의에서 배우셨던 랜덤 테스트에 대해 다시금 잘 상기해보시면서 코드를 작성해보시면 충분히 해당 테스트를 잘 작성하실 수 있을거예요 :)

코멘트 남겨두었으니, 확인 후 다시 리뷰 요청 부탁드릴게요!

2022-12-28 15:23 UTC, malibinYun commented on src/main/kotlin/minesweeper/domain/button/ButtonGraph.kt
> +        )
col에 대한 Buttons를 추가할 때 난해해질 것으로 예상되어요.
해당 메서드를 외부에서 사용하지 않고 있기도 하니, rowButtons에 녹여내는 게 가장 나아 보여요 :)

2022-12-28 15:23 UTC, malibinYun commented on src/main/kotlin/minesweeper/domain/button/Buttons.kt
> +) : List<Button> by buttons
해당 일급 컬렉션은 맡은 일이 거의 없어 불필요해 보입니다.
ButtonGraph 일급 컬렉션과 역할이 겹쳐보이기도 하네요 :)

2022-12-28 15:23 UTC, malibinYun commented on src/main/kotlin/minesweeper/domain/position/Positions.kt
> +) : List<Position> by positions {
https://github.com/next-step/kotlin-minesweeper/pull/207#discussion_r1057096726
이 부분은 위 리뷰 내용과 같은 맥락이겠네요 :)

2022-12-28 15:23 UTC, malibinYun commented on src/main/kotlin/minesweeper/domain/position/vendor/PositionsVendor.kt
> +    ): Positions {
범위가 꼭 필요한지 모르겠어요. 오히려 다른 개발자들이 해당 메서드를 활용할 때 실수를 불러일으킬 수 있어 보입니다.
또, totalCount 라는 이름만으로는 지뢰의 갯수를 의미한다고 생각하기에는 어려워 보입니다.

기준을 항상 0,0 (혹은 1,1)으로 잡고, 위치들을 만드는 것은 어떨까요?
다른 기준이 존재하면, 디버깅 할 때나,  다른 사람들이 생각할 때 굉장히 난해해질 것이 우려되어요.

2022-12-29 06:29 UTC, rolroralra commented on src/main/kotlin/minesweeper/domain/MineSweeperGame.kt
> +    val totalMineCount: Int = buttonGraph.totalMineCount
넵 게임의 전반적인 진행의 역할을 하는 객체로 설계하려 하였습니다.

현재 출력관점에서는 `height`, `width`, `totalMineCount`를 사용하지 않으므로,

리뷰 주신대로 추후 다음 단계에서의 요청사항에 따라 추가하도록 하겠습니다.

리뷰 감사합니다.

2022-12-29 06:30 UTC, rolroralra commented on src/main/kotlin/minesweeper/domain/MineSweeperGame.kt
> +    }
좀 궁금한게 있는데, 

부생성자가 여러개 있는게 좋을까요 아니면, 생성자는 오로지 한개이고 

그외에 것들은 팩토리 메서드로 하는게 좋을까요?

2022-12-29 06:30 UTC, rolroralra commented on src/main/kotlin/minesweeper/domain/button/ButtonGraph.kt
> +    val totalMineCount: Int,
`MineSweeperGame`과 마찬가지로 필요할때 추가하도록 하겠습니다.

리뷰 감사합니다.

2022-12-29 06:33 UTC, rolroralra commented on src/main/kotlin/minesweeper/domain/button/ButtonGraph.kt
> +        )
동일한 기능이지만, operator 같은걸 써보고 싶은 궁금함에 가능한것들 모두 추가하다 보니 이리 됬네요.

말씀대로 메서드를 최대한 필요한 부분만 구현토록 하겠습니다.

리뷰 감사합니다.

2022-12-29 07:32 UTC, rolroralra commented on src/main/kotlin/minesweeper/domain/button/Buttons.kt
> +) : List<Button> by buttons
현재 사용되고 있습니다. 

출력부분에서 확장함수 정의할때, `joinString`을 사용하기 때문에,

일반적인 immutableList 인터페이스를 제공하는것이 맞다고 생각합니다.

`Buttons`객체 자체가 `Button`객체를 List로 가지는 객체이므로, 

List 위임하는게 더 편하다고 생각을 합니다.

게다가 List인터페이스 모두를 공개한다고 해서, 객체 내부 상태가 바뀌는게 아니므로

크게 상관없다고 생각합니다.

2022-12-29 17:43 UTC, rolroralra commented on src/main/kotlin/minesweeper/domain/position/Positions.kt
> +) : List<Position> by positions {
일급컬렉션 객체를 의도한거라서,

혹시 어떤 문제점이 있는지 조언좀 부탁드립니다.

2022-12-29 17:43 UTC, rolroralra commented on src/main/kotlin/minesweeper/domain/position/vendor/PositionsVendor.kt
> +    ): Positions {
리뷰 감사합니다.

반영하겠습니다.

2022-12-30 13:51 UTC, malibinYun commented on src/main/kotlin/minesweeper/domain/button/Buttons.kt
> +) : List<Button> by buttons
네 :) 객체에게 필요 없는 메서드들도 목록에 존재해서 역할에 맞는 메서드가 묻힐 수 있는 단점도 있겠지만,
편리성에 더 중점을 둔다면 이보다 더 편리한 것은 없으니 선택하는 게 맞지요! 🙂


다만, java kotlin을 같이 사용하는 프로젝트에서는 굉장히 유의해야합니다.
Java 코드에서 해당 kotlin 코드를 사용하게 되면, Kotlin에서는 immutable한 로직일지라도 Java에서는 List가 Mutable이기 때문에 add 등의 메서드들의 호출이 가능합니다 :)

2022-12-30 13:51 UTC, malibinYun commented on src/main/kotlin/minesweeper/domain/MineSweeperGame.kt
> +    }
취향 차이라고 생각해요 :)
다만, 생성자 혹은 팩터리 메서드 둘 중 하나만 사용하는 것이 바람직하다고 생각해요.
팩터리 메서드가 있으면 기본 적인 생성자는 private하게 막아서 원치 않은 생성을 막는 게 낫다고 생각합니다.
이것 조차도 취향의 영역일 수 있겠네요 :)

2022-12-30 14:03 UTC, malibinYun approved these changes
1단계 미션 피드백 반영하시느라 고생 많으셨어요~!
다음 미션을 위해 머지하겠습니다 :)
몇 가지 코멘트를 남겨두었으니 확인 부탁드릴게요!

2022-12-30 14:03 UTC, malibinYun commented on src/main/kotlin/minesweeper/domain/MineSweeperGame.kt
> +    private val buttonVendor: ButtonVendor
ButtonVender를 외부에서 주입받을 수 있다면, 원하는 위치의 ButtonGraph가 생성되었는지도 테스트해볼 수 있겠네요 :)

2022-12-30 14:03 UTC, malibinYun commented on src/main/kotlin/minesweeper/domain/position/vendor/PositionVendor.kt
> +
이 부분도 positions를 외부에서 주입받을 수 있게 만들면 손쉽게 모킹을 해볼 수 있겠네요 :)

2022-12-30 14:03 UTC, merged

2022-12-30 14:33 UTC, rolroralra commented on src/main/kotlin/minesweeper/domain/button/Buttons.kt
> +) : List<Button> by buttons
java 같이 쓰는 경우는 조심해야겠네요.

리뷰 감사합니다.

2022-12-30 17:59 UTC, rolroralra commented on src/main/kotlin/minesweeper/domain/position/Position.kt
> +        comparator().compare(this, other)
리뷰 감사합니다.

Vendor쪽 mocking 테스트 경우는 2,3,4단계 진행하면서,

반영하게되면 말씀드리겠습니다.

2022-12-30 17:59 UTC, rolroralra commented on src/main/kotlin/minesweeper/domain/position/vendor/PositionVendor.kt
> +
리뷰 감사합니다.

Vendor쪽 mocking 테스트 경우는 2,3,4단계 진행하면서,

반영하게되면 말씀드리겠습니다.

2022-12-30 18:00 UTC, rolroralra commented on src/main/kotlin/minesweeper/domain/MineSweeperGame.kt
> +    private val buttonVendor: ButtonVendor
리뷰 감사합니다.

Vendor쪽 mocking 테스트 경우는 2,3,4단계 진행하면서,

반영하게되면 말씀드리겠습니다.

2022-12-30 18:00 UTC, rolroralra commented on src/main/kotlin/minesweeper/domain/MineSweeperGame.kt
> +    }
넵 말씀대로, 한쪽으로 맞쳐서 설계하는게 맞는거 같네요.

리뷰 감사합니다.