🔥 2단계 - 지뢰 찾기(지뢰 개수)
next-step/kotlin-minesweeper pull request #208
Opened 2022-12-25 18:48 UTC by heedoitdox

안녕하세요 동철님! 크리스마스는 잘 보내셨나요? 🎄 눈이 안와서 아쉽네요....ㅎㅎ
이번 단계도 잘 부탁드립니다 🥰

저번 단계 피드백에서 CellGenerator 를 interface 로도 구현해볼 수 있을 것 같다고 하셨었는데요!
빈칸 생성에서 주위 지뢰의 수를 카운팅하는 부분에서 추가하거나 달라질 부분이 있을 것 같아 CellGenerator 를 인터페이스로 고치고
MineGenerator, BlankGenerator 클래스를 나누어 구현해보았습니다..! 

그리고 한가지 질문사항이있는데요😊
`객체지향생활체조원칙에서 모든 원시값을 포장한다` 라는 원칙이 있는데
제 코드를 보시면,,, 단순한 x, y 좌표는 Int 값으로 주고 받고 있습니다. 요 x, y 는 아무런 조건에 제한되지 않는 `Int` 그 자체여서인데요...
요런 경우에도 값객체로 포장을 하는것이 좋은가요? 
아니면 뭔가 행위를 더 부여할 수 있는데 현재 단계에서는 필요없기 때문에 제가 포장의 필요성을 못느낀 걸까요...?
리뷰어님의 생각이 궁금합니당!!

2022-12-27 02:17 UTC, sah3122 commented
2단계 미션 구현도 너무 잘해주셨습니다  💯 

질문주신 내용에 대해 제 생각을 남겨드릴게요 😄 
```
단순한 x, y 좌표는 Int 값으로 주고 받고 있습니다. 요 x, y 는 아무런 조건에 제한되지 않는 Int 그 자체여서인데요...
요런 경우에도 값객체로 포장을 하는것이 좋은가요?
아니면 뭔가 행위를 더 부여할 수 있는데 현재 단계에서는 필요없기 때문에 제가 포장의 필요성을 못느낀 걸까요...?
```

우선 제가 느끼기엔 x, y 좌표를 나타낼수 있는 Coordinate 객체(row, col)를 만들어두고, 사용하지 않고 있는것이 아쉬웠습니다. 
분명히 행위를 더 부여할수 있는 상황이 있을건데, 현재 필요가 없다고 느꼇기 때문에 사용하지 않아서 캡슐화를 할수 있는 부분이 외부로 노출된것들이 있는것 같아요 😄 

이번 과정은 학습의 과정이니 최대한 포장된 값을을 사용해보고 필요한 시점에 행위까지 부여할수 있으면 좋을것 같아요 🙏

2022-12-27 02:18 UTC, sah3122 requested changes
안녕하세요 영빈님 😄 
2단계 미션도 너무 구현 잘해주셨습니다 💯 
몇가지 생각거리와 질문에 대한 제 생각을 남겨두었는데 확인 부탁드려요 ! 
제가 남겨둔 코멘트를 모두 반영해주실 필요는 없으니 참고 부탁드립니다 🙏

2022-12-28 23:11 UTC, heedoitdox commented on src/main/kotlin/domain/BlankGenerator.kt
> +            Blank.from(x, y, minesAroundCount)
음 사실은 후자의 방법을 처음에 생각했었는데요,
후자 방법을 적용한다 했을 때,`Board` 객체에서는 List<Cell> 프로퍼티를 갖고있기 때문에 Blank 인 cell 만 필터링해서 지뢰 갯수를 카운팅하고 저장하고 ... 그렇게 되면 결국 Board 에서 List<Blank>, List<Mine> 을 따로 갖고 있는게 편하지않을까? -> 그러면 뭐하러 sealed class 를 사용했을 까? -> 생성할 때 그냥 찾아버리면 출력할 때 빼고는 Blank,Mine 필터링을 하지 않아도 되지않을까?
하는 생각의 흐름에서 생성할 때 지뢰갯수를 계산하도록 구현했습니다..

그런데 사실 제가 구현한 방법은 Board 에 메세지를 던져 지뢰 셀을 알아내기 때문에 무조건 Blank 셀을 생성하기전에 지뢰 셀로 이루어진 보드가 생성되어있어야 한다 라는 전제조건이 있어서 로직이 다소 띠용?스럽긴합니다.. 🤯
코멘트를 달면서 생각해보니 뭔가 빈칸 셀을 생성할 때 이상한 의존도가 있는 것 같네요..! 후자의 방법으로 진행해 보아야겠습니당 ㅎ😊

2022-12-29 12:48 UTC, heedoitdox commented on src/main/kotlin/domain/Game.kt
> +        board.addAll(blankCells)
처음에 셀 생성 로직을 분리했던 이유는 랜덤값의 대한 생성 테스트를 편하게 하려고 였는데요,
(CellGenerator().generate() 에서 안에 private fun 으로 나누어 한 번에 생성 할 수도 있지만 그렇게 되면 디테일한 테스트가 어렵기때문이라고 생각)
어떻게 개선할까 생각하다 보니 1단계 미션때 사용했던 전략패턴을 여기에도 다시 적용한다면
가독성도 높히고 테스트도 용이하게 할 수 있겠더라구요 그래서 말씀해주신대로 셀 생성 generator 를 분리하지않고 하나로 사용하면서
전략패턴을 사용하여 테스트 할 수 있도록 개선해 보았습니다!

2022-12-29 12:50 UTC, heedoitdox commented
안녕하세요 동철님 😊
주신 피드백 모두 반영할 필요는 없다고 해주셨었는데 말씀해 주신 부분 공감이 되어 하나 둘 씩 변경하다보니 결국 다 반영해버리게 되었는데
이전보다는 깔끔하고 가독성이 좋아진 느낌이 듭니다 👍

2022-12-30 15:45 UTC, sah3122 approved these changes
피드백 반영 너무 잘해주셨습니다 💯 
처음 구현해주신 코드도 훌륭했지만 가독성이 더 좋아진것을 느낄수 있었어요. 
다음 미션도 기대하겠습니다 🙏

2022-12-30 15:45 UTC, sah3122 commented on src/main/kotlin/domain/Board.kt
> +            it.changeMinesAroundCount(minesAroundCount)
주변 지뢰의 수를 구하는 로직이 깔끔해졌네요 😄

2022-12-30 15:45 UTC, sah3122 commented on src/main/kotlin/domain/CellGenerator.kt
> +class CellGenerator {
지뢰 찾기 미션에 사용할 Cell을 생성하는 로직이 캡슐화 된것이 인상적입니다 👍

2022-12-30 15:45 UTC, sah3122 commented on src/main/kotlin/domain/Coordinate.kt
> +    constructor(value: Pair<Int, Int>) : this(Number(value.first), Number(value.second))
pair를 인자로 받는 secondary 생성자 활용 👍

2022-12-30 15:45 UTC, merged