Step2 - 지뢰 찾기(지뢰 개수)
next-step/kotlin-minesweeper pull request #209
Opened 2022-12-26 14:05 UTC by harrisleesh

안녕하세요! 2단계 구현하여 리뷰 요청드립니다. 
최대한 함수를 분리하고 간결한 코드를 짜려 노력했습니다.

상세한 리뷰와 피드백 부탁드립니다!!
매번 감사드립니다!

2022-12-27 13:23 UTC, hyunniiii requested changes
안녕하세요 ~
간단하게 몇가지 코멘트 남겼으니 확인 부탁드립니다!

2022-12-27 13:23 UTC, hyunniiii commented on src/main/kotlin/minesweeper/domain/MineBoard.kt
>      val mineCells: Array<MineBoardRow>,
`Array`를 사용하신 이유가 있으실까요?

2022-12-27 13:23 UTC, hyunniiii commented on src/main/kotlin/minesweeper/domain/MineBoardRow.kt
>      constructor(width: Int) : this(Array(width) { CleanCell() })
kotlin 컨벤션에 따르면  생성자는 메서드보다 위쪽에 위치해야합니다. :) 

https://kotlinlang.org/docs/coding-conventions.html#class-layout

2022-12-27 13:23 UTC, hyunniiii commented on src/main/kotlin/minesweeper/domain/Position.kt
> +data class Position(val height: Int, val width: Int) {
`Position`에 대한 테스트도 추가할 수 있을 것 같아요~

추가로 `Position`은 `Cell`이 상태로 가지고 있도록 하는건 어떨까요?
자기 자신의 위치는 `Cell` 이 알고 있어도 괜찮을 것 같습니다 :)

2022-12-27 13:23 UTC, hyunniiii commented on src/main/kotlin/minesweeper/domain/MineBoard.kt
> +    }
`Array<MineBoardRow>` 타입의 객체를 한번 생성해주고 값을 변경하고 있는 것 같아요.
이럴경우 의도하지 않은 값으로 변경될 가능성이 높아집니다.

main에서 `mineBoard.mineCells[3].mineCells[2] = CleanCell()` 이렇게 접근도 가능합니다.
최대한 불변을 이용해주시고 값을 나중에 설정해주기보다는 초기화 시에 바로 설정할 수 있도록 해보는건 어떨까요? 😄

2022-12-28 02:33 UTC, harrisleesh commented on src/main/kotlin/minesweeper/domain/MineBoard.kt
>      val mineCells: Array<MineBoardRow>,
앗 넵! 혹시 List 대신 Array를 사용한 이유를 물어보신거라면
Array가 검색속도가 빠르고 해당 지뢰찾기 행을 삭제할 일이 없기때문에 리스트보다 Array가 좋을것이라 생각해서 사용했습니다!

2022-12-28 02:36 UTC, harrisleesh commented on src/main/kotlin/minesweeper/domain/MineBoardRow.kt
>      constructor(width: Int) : this(Array(width) { CleanCell() })
오 그렇군요!! 공식문서 링크 감사합니다!!

2022-12-28 02:45 UTC, harrisleesh commented on src/main/kotlin/minesweeper/domain/Position.kt
> +data class Position(val height: Int, val width: Int) {
오 이부분을 수정하는 걸 고민해봤는데 설계가 많이 변화하게 되는 것 같네요!
제안해주신 방향이 보다 객체지향적인 설계가 될 것 같네요!!
감사합니다!! 반영하도록 해볼게요!!

2022-12-28 06:26 UTC, harrisleesh commented
피드백주신 Cell이 position을 갖고있는 것과 불변성을 적용하라는 리뷰가 많은 도움이 되었습니다.
덕분에 설계 구조가 꽤 많이 변경되었네요:
다시 한 번 상세한 리뷰 부탁드려요!!

2022-12-29 14:01 UTC, hyunniiii approved these changes
안녕하세요~
피드백 반영 잘해주셨습니다 :) 
코멘트 몇개 남겼으니 다음 미션과 함께 확인부탁드립니다.
이번 미션은 머지할게요!

2022-12-29 14:01 UTC, merged

2022-12-30 03:17 UTC, harrisleesh commented on src/main/kotlin/minesweeper/domain/MineBoard.kt
> +    private val mineCells: Map<Position, Cell>,
오 넵 생각해보니 맵을 초기화하는 등 맵과 관련된 책임과 보드와 게임과 관련된 책임이 섞여있는 듯 하네요!!
감사합니다! 해당부분을 리팩토링 해보겠습니다:)

2022-12-30 07:02 UTC, harrisleesh commented on src/main/kotlin/minesweeper/domain/Position.kt
> +data class Position(val row: Int, val column: Int) {
오 넵 일급 컬렉션으로 생성하면 좋을 것 같아서 해당 클래스를 만들어 봤습니다.