🔥 3단계 - 지뢰 찾기(게임실행)
next-step/kotlin-minesweeper pull request #226
Opened 2022-12-31 10:17 UTC by heedoitdox

안녕하세요 동철님 😊
3단계 리뷰도 잘 부탁드립니다! 

질문은 코드에 코멘트로 남겨놓을게요!

2022-12-31 10:24 UTC, heedoitdox commented on src/main/kotlin/domain/Game.kt
> +    }
3단계에서 지뢰의 좌표를 오픈하지 않으면 무한으로 게임을 실행할 수 있게되면서 
inputView, ResultView 를 람다식 인자로 넘겨받게 구현했는데요,
이렇게 구현하니 입력값을 어떻게 테스트(ex. 모든 빈칸이 오픈되어있다면 게임이 끝나고 승리한다. ) 해야할지 고민이 되네요 😂😂 제가 테스트를 할 수 없게 만들어버린 건가요?

2022-12-31 10:27 UTC, heedoitdox commented on src/main/kotlin/view/ResultView.kt
> +    }
사실 처음에 controller 에서 
```kotlin
runCatching {
    game.play(
        board,
        inputCoordinate = { InputView.inputCellToOpen() },
        printBoard = { boardInfo, boardDto -> ResultView.printBoard(boardInfo, boardDto) }
    )
}.onSuccess {
    ResultView.printWin(boardInfo, BoardDto.from(board))
}.onFailure {
    ResultView.printLose()
}
```
이렇게 구현했었는데 테스트를 위해서 `ResultStatue` enum class 를 만들고 반환하게 만들었는데요
그러다 보니 `printResult` 에서 객체지향생활체조 원칙중 하나인 else 를 쓰지 않는다를 어기게 되어버렸습니다... 

sealed class 도 생각해보았는데 딱히 class 내용에 들어갈 것이 없어보여 enum class 를 사용하는 것이 더 적합하다는 생각이 들었는데요..!
sealed class 반환하여 when 절을 else 없이 쓰게된다면 이는 위반하지 않았다고 볼 수 있는걸까요?

2022-12-31 13:06 UTC, heedoitdox commented on src/main/kotlin/domain/Game.kt
> +    }
음 생각하다보 승, 패 결과는 요렇게 테스트 할 수 있을 것 같아서 테스트 코드 추가했습니다!
- [c528996](https://github.com/next-step/kotlin-minesweeper/pull/226/commits/c52899623760371d83487d9ecf903d89c23adcb4)
- [3189294](https://github.com/next-step/kotlin-minesweeper/pull/226/commits/3189294c2d7d7a3782f743e655a397bcfe639457)

그런데 추가적으로 여러 좌표들을 입력받은 결과를 테스트하는 부분이 조금 아쉽게 느껴지네요..
리뷰어님의 의견이 궁금합니다..! 😊
(ex. 빈칸을 오픈 -> 빈칸을 오픈 -> 지뢰 오픈 -> LOSE)
(ex. 빈칸 오픈 -> ..... -> WIN)

2023-01-01 12:42 UTC, sah3122 requested changes
3단계 미션 구현 잘해주셨습니다 👍 
특별한 코멘트 보단 남겨주신 질문에 대한 제 생각을 적어보았어요 ! 
확인 부탁드려요 🙏

2023-01-01 13:45 UTC, heedoitdox commented on src/main/kotlin/domain/Game.kt
> +    }
감사합니다! 피드백 주신대로 play 의 반복문의 대한 로직을 controller 의 private 함수로 빼고 Game 객체에서는 단순한 행위만을 부여하여 테스트 케이스를 작성하는 방향으로 개선해 보았습니다..!

2023-01-01 13:47 UTC, heedoitdox commented on src/main/kotlin/view/ResultView.kt
> +    }
early return 이라는 패턴이있군요! state pattern 은 일전에 제이슨께서 강의해주신 블랙잭 피드백에서 나왔던 패턴 말씀하시는 거죠?
디자인 패턴에 대해서도 공부할 것들이 많네요 😂
해당 로직은 위 리뷰에서 리팩터링을 진행하면서 사라졌습니다!
exception 의 대한 피드백도 감사해요! 😊

2023-01-01 13:49 UTC, heedoitdox commented
주신 피드백 반영해 보았습니다! 더불어 좋은 의견 감사드려요 🥰

2023-01-02 13:31 UTC, sah3122 requested changes
피드백 반영 잘해주셨습니다 👍 
한가지 아쉬운 부분이 있어 코멘트 남겨두었는데 확인 부탁드려요 🙏 
미션 기간이 끝나도 리뷰는 진행되니 천천히 진행해주셔도 됩니다 😄

2023-01-02 13:31 UTC, sah3122 commented on src/main/kotlin/controller/MinesweeperController.kt
> +        }
`board.isOpenAllBlank`와 같은 메소드를 활용하여 board 내부 상태값에 대해 메시지를 던지는것보단 board가 상태를 가질수 있도록 구현해보는건 어떨까요 ? 

추가로 `board.isMineCell(coordinate)`를 먼저 확인하여 게임을 종료하는것이 자연스러운지, `val cell = board.open(coordinate)` 와 같은 메소드를 제공하는것이 자연스러운지 고민해보세요. 
여기서 자연스럽다는 의미는 도메인 모델링이 자연스러운지에 대한 물음입니다. 😄

2023-01-03 18:10 UTC, heedoitdox commented on src/main/kotlin/controller/MinesweeperController.kt
> +        }
Game 객체에 `GameStatus` 상태를 추가하여 while 문에서 Game 객체의 상태로 판별하여 종료될 수 있도록 개선해 보았습니다!
그리고 추가로 말씀해주신 부분은 잘 이해가 가지 않습니다 😂

제가 개선한 부분을 먼저 말씀 드리자면

- AS-IS
```kotlin
while (!board.isOpenAllBlank) {
            val coordinate = InputView.inputCellToOpen()
            if (board.isMineCell(coordinate)) return ResultView.printLose()
            val blank = game.getBlankCell(coordinate, board)
            board.openAdjacentBlanksBy(blank)
            ResultView.printBoard(BoardDto.from(board, game.boardInfo.column))
        }
 ```

- TO-BE
```kotlin
while (game.isProceeding) {
            val coordinate = InputView.inputCellToOpen()
            game.openCell(board, coordinate)
            ResultView.printBoard(BoardDto.from(board, game.boardInfo.column))
        }
```

로 변경되었고 `isMineCell` 은 game.openCell 에서 처리하게 되었는데요!
말씀해주신 `val cell = board.open(coordinate)` 와 같은 메소드를 제공해서 처리했을 때
cell 은 Cell? 로 반환되는 것을 말씀하신걸까요??
만약 제가 이해한 바가 맞다면 
저 메소드를 제공했을때 그 아래 nullable 의 대한 처리 (없는좌표), 지뢰좌표일때의 처리를 해줘야해서 결국 `isMineCell` 메서드로 먼저 확인하는것과 다를 바 없지 않나용..? 👀
아니면 혹시 처음에 말씀해주신 방향은 controller 에서 board 객체에게 저 메세지를 보내는 것이 자연스럽지 않다고 느끼셔서 피드백주신걸까요?

2023-01-05 00:27 UTC, sah3122 commented on src/main/kotlin/controller/MinesweeperController.kt
> +        }
처음 구현 해주신 코드는 현재 요구사항은 만족하나, 확장이 어려운 구조라고 느껴졌습니다. 
요구사항을 만족하기 위해 
1. 입력 받은 좌표가 지뢰인지 확인 (isMineCell)
2. 지뢰가 아니라면 좌표에 해당하는 Cell 을 조회 (getBlankCell)
3. 보드에게 Blank를 전달하고, 지뢰가 아닌 주변 Cell을 모두 오픈 (openAdjacentBlanksBy)
라는 프로세스를 따르고 있어요. 

입력 받은 좌표에 해당하는 Cell 을 리턴 받고, Cell 을 `조회한 객체`에서 Cell 의 타입에 따라 프로세스를 정의할수 있는 구조로 리팩토링 하는것을 제안 드린것이며 예를 들면 아래와 같은 프로세스로 변경이 되는것을 기대했습니다. 

1. 입력 받은 좌표의 Cell 을 조회하여 리턴

여기서 지뢰를 리턴하였다면 지뢰찾기 게임은 종료가 될것이고, 빈칸이 리턴되었다면 보드 출력과 게임이 계속 진행되었을거라고 생각합니다. 

AS-IS 와 TO-BE의 차이점은 비즈니스 로직이 외부로 노출되어있는지에 대한 차이라고 생각합니다. 
중요한 비즈니스 로직을 캡슐화 함으로서 얻을수 있는 장점에 대해 고민해보세요 !

2023-01-05 00:42 UTC, sah3122 requested changes
피드백 반영 잘해주셨습니다 👍 
한가지 코멘트 남겨두었는데 확인 부탁드려요 😄 
반드시 적용할 필요는 없습니다 ㅎㅎ 
다음 요청시 머지하도록 할게요 💯

2023-01-05 00:42 UTC, sah3122 commented on src/main/kotlin/domain/Game.kt
> +        }
코멘트에 남겨두었는데 board 의 상태값을 조회하기 보단 메시지만 던지는 구조로 변경이 가능할까요 ?

2023-01-05 15:43 UTC, heedoitdox commented
동철님!
피드백주신대로 
>입력 받은 좌표의 Cell 을 조회하여 리턴
하는 방식으로 개선해 보았습니다 🙂

2023-01-07 13:20 UTC, sah3122 commented on src/main/kotlin/domain/Game.kt
> +        }
상태값을 조회하여 행위를 호출하는 구조만 봐서는 동일하다고 생각하나 현재 구조에서는 영빈님이 이야기해주시는 부분도 맞는것 같아요 😄

2023-01-07 13:23 UTC, sah3122 approved these changes
마지막 피드백까지 반영 잘해주셨습니다 👍 
4단계 미션은 TDD를 활용한 리팩터링 미션인데, 지금도 충분히 잘해주셨다고 생각해요. 
4단계 미션은 영빈님이 판단하여 진행 또는 마무리 해주시면 좋을것 같습니다. 😄

2023-01-07 13:23 UTC, merged