Step1 지뢰 찾기(그리기)
next-step/kotlin-minesweeper pull request #260
Opened 2023-06-28 14:57 UTC by minhyukseul

스텝1 PR요청드립니다.
점진적인 리팩토링을 통해 테스트 코드가 변경이 될 때 어떻게 하면 덜 건드릴 수 있는지 등에 대해서 고민해 봤습니다.

2023-06-30 16:16 UTC, kyucumber requested changes
리뷰가 다소 늦었습니다.

몇가지 코멘트 남겨두었으니 확인 부탁드릴게요.

2023-06-30 16:16 UTC, kyucumber commented on src/main/kotlin/minesweeper/domain/MineMap.kt
> +        val tile = mineMap[positionX][positionY]
Pair 타입이라 아래처럼 사용할 수 있을 것 같네요.

```suggestion
        val (x, y) = position
        val tile = mineMap[x][y]
```

2023-06-30 16:16 UTC, kyucumber commented on src/main/kotlin/minesweeper/domain/MineMap.kt
> +            "지뢰는 넓이*너비의 수보다 작거나 같아야한다"
게임의 모든 칸이 지뢰인 경우면 게임 자체가 성립이 되지 않을 것 같은데요. 최소 한칸은 일반 타일이어야 하지 않을까요?

2023-06-30 16:16 UTC, kyucumber commented on src/main/kotlin/minesweeper/domain/MineMap.kt
> +        return makeCount.inc()
지뢰인 경우 makeCount의 inc가 호출되지 않아야 중복된 좌표에 지뢰 마킹을 한 경우에도 정상적으로 10개를 다 채울 수 있지 않을까요? 한번 확인 부탁드릴게요.

2023-06-30 16:16 UTC, kyucumber commented on src/main/kotlin/minesweeper/domain/RandomPosition.kt
> +            return positionX to positionY
지금은 간단하기 때문에 크게 상관 없으나, `Pair<Int, Int>`와 `Pair<String, String`과 같은 타입은 각각의 타입이 어떤 것을 의미하는지 알기 어려운 경우가 많습니다. Pair 대신 데이터 클래스로 만들어도 큰 추가 비용이 들지 않으며 다음과 같은 장점이 있습니다.

- 함수의 리턴 타입이 더 명확해진다.
- 리턴 타입이 더 짧아지며 전달하기 쉬워진다.
- 사용자가 데이터 클래스에 적혀있는 것과 다른 이름을 활용해 변수를 해제하면, 경고를 출력한다.

변경하실 필요는 없으나 이후는 data class의 사용을 고려해보셔도 좋을 것 같습니다.

2023-06-30 16:16 UTC, kyucumber commented on src/main/kotlin/minesweeper/view/OutputView.kt
> +        if (tileColumn[position].isMine()) {
코드의 일관성이 없네요. IDE의 코드 포매팅 기능을 활용해보시면 좋겠습니다.
혹은 ktlint를 로컬에 설치하고 프리 커밋 훅을 통해 ktlint를 돌려보아도 좋을 것 같습니다.

- `if(`
- `if (`

2023-06-30 16:16 UTC, kyucumber commented on src/test/kotlin/minesweeper/domain/HeightTest.kt
> +    @Test
AnnotationSpec은 Junit에서 Kotest로 마이그레이션 하는 경우 권장하며, 굳이 `@Test` 어노테이션을 쓸 필요 없이 funSpec이나 stringSpec등을 활용해보셔도 좋을 것 같아요.

2023-07-01 00:18 UTC, minhyukseul commented on src/main/kotlin/minesweeper/domain/Height.kt
> +            "높이는 숫자이어야함"
수정해보았습니다.

2023-07-01 00:18 UTC, minhyukseul commented on src/main/kotlin/minesweeper/domain/MineCount.kt
> +value class MineCount(private val count: String) {
여기도 수정해보았습니다.

2023-07-01 00:19 UTC, minhyukseul commented on src/main/kotlin/minesweeper/domain/MineMap.kt
> +    }
이름 짓는게 가장 어려운거 같습니다. 말씀주신 이름이 더 적절해 보이네요.

2023-07-01 00:19 UTC, minhyukseul commented on src/main/kotlin/minesweeper/domain/MineMap.kt
> +        val tile = mineMap[positionX][positionY]
말씀 주신 내용으로 수정해보았습니다.

2023-07-01 00:20 UTC, minhyukseul commented on src/main/kotlin/minesweeper/domain/MineMap.kt
> +            "지뢰는 넓이*너비의 수보다 작거나 같아야한다"
제가 지뢰게임 도메인에 대한 이해도가 낮은거 같네요. 수정하였습니다.

2023-07-01 00:22 UTC, minhyukseul commented on src/main/kotlin/minesweeper/domain/MineMap.kt
> +        return makeCount.inc()
말씀 주신것처럼 로직에 오류가 있는것 같네요 수정하였습니다.

2023-07-01 00:23 UTC, minhyukseul commented on src/main/kotlin/minesweeper/domain/RandomPosition.kt
> +            return positionX to positionY
말씀주신 내용대로 해서 고려해서 수정이 필요할 것 같습니다. 추후 미션에 말씀주신 사항을 반영해 보도록 하겠습니다.

2023-07-01 00:25 UTC, minhyukseul commented on src/main/kotlin/minesweeper/view/OutputView.kt
> +        if (tileColumn[position].isMine()) {
벌써 4번째 미션인데 이런 초보적인 실수를 하였네요.

2023-07-01 00:27 UTC, minhyukseul commented on src/test/kotlin/minesweeper/domain/HeightTest.kt
> +    @Test
funSpec을 한번 활용해 보도록 하겠습니다.

2023-07-01 09:23 UTC, kyucumber approved these changes
피드백 잘 반영해주셨습니다.

다음 단계 진행을 위해 머지할게요

2023-07-01 09:23 UTC, merged