Step4 지뢰게임(리팩토링)
next-step/kotlin-minesweeper pull request #339
Opened 2023-07-10 06:38 UTC by minhyukseul

TDD를 이용하여 구현하였습니다.

마지막 미션인데도 TDD가 아직 익숙하지 않아 시간이 많이 걸리네요.

한가지 질문이 있습니다. return 타입에 대해서 shouldThrow를 사용할 수가 없는데 저런 경우는 어떻게 테스트를 해야 할런지요.
MinesWeeperGameTest의 "입력받은 위치는 높이와 넓이보다 작거나 같아야한다" 이 부분의 두번째 테스트 구간입니다.

2023-07-10 13:37 UTC, kyucumber requested changes
마지막 스텝까지 수고 많으셨습니다.

간단한 코멘트만 몇개 남겨두었으니 확인 부탁드려요.

2023-07-10 13:37 UTC, kyucumber commented on src/test/kotlin/minesweeper/domain/MinesWeeperGameTest.kt
> +    "입력받은 위치는 높이와 넓이보다 작거나 같아야한다" {
> 한가지 질문이 있습니다. return 타입에 대해서 shouldThrow를 사용할 수가 없는데 저런 경우는 어떻게 테스트를 해야 할런지요.
MinesWeeperGameTest의 "입력받은 위치는 높이와 넓이보다 작거나 같아야한다" 이 부분의 두번째 테스트 구간입니다.

2023-07-10 13:37 UTC, kyucumber commented on src/test/kotlin/minesweeper/domain/MinesWeeperGameTest.kt
> +    "입력받은 위치는 높이와 넓이보다 작거나 같아야한다" {
아래처럼 작성해주시면 됩니다. `getOpenPosition`에서 범위를 넘는 MinePosition을 넘기면 호출 시점에 예외가 발생하고 테스트 조건을 통과할 것 같네요.

```kotlin
        shouldThrow<IllegalArgumentException> {
            gameMap.openTile(object : GameStateNotify {
                override fun getOpenPosition(): MinePosition {
                    return MinePosition.of(?, ?) // 여기에 예외가 발생하는 값을 지정
                }

                override fun showGameState(status: GameStatus) {
                    status shouldBe GameStatus.CONTINUE
                }

                override fun showMineMapInProgress(mineMap: MinesMap) {
                }
            })
        }
```

2023-07-10 13:37 UTC, kyucumber commented on src/main/kotlin/minesweeper/MineSweeperGameMain.kt
> +    })
이 부분은 SAM Conversion을 적용하면 아래처럼 깔끔하게 lambda로 작성할 수 있습니다.

```suggestion
    gameMap.generateMine { minePosition }
```

2023-07-10 13:37 UTC, kyucumber commented on src/main/kotlin/minesweeper/MineSweeperGameMain.kt
> +    })
https://kotlinlang.org/docs/fun-interfaces.html

위 문서를 읽어보시면 될 것 같아요. 일단 핵심은 기존 인터페이스가 아래처럼 fun interface로 정의되어야 SAM Conversion을 사용할 수 있다는 점입니다. 이 부분은 코틀린의 버전이나 세부적인 부분에 따라 변경되었거나 변경될 수 있으니 참고 부탁드려요.

```kotlin
fun interface MinePositionGenerator {
    fun generatePosition(): MinePosition
}
```

2023-07-10 13:37 UTC, kyucumber commented on src/main/kotlin/minesweeper/domain/MineRow.kt
> +        }
중요한 부분은 아니나 일관성 있는 방식으로 코드가 작성되면 좋겠습니다.

리뷰 남겨드린 부분만 변경하신 것 같은데 for문을 사용하셔도 상관없으니 같은 역할을 하는 코드는 동일한 구문을 사용해 작성해주시면 좋겠네요~ 문법이 여러개 섞여있어 오히려 헷갈릴 수 있을 것 같아요.

2023-07-10 13:37 UTC, kyucumber commented on src/main/kotlin/minesweeper/domain/MineRow.kt
> +    }
```suggestion
    fun sizeOfRemainTiles(): Int = rows.filterNot {
            it.isOpen
        }.size
```

2023-07-10 13:37 UTC, kyucumber commented on src/main/kotlin/minesweeper/domain/MineRow.kt
> +    }
코틀린에서는 메서드 체이닝 등을 통해 간단하게 리턴이 가능한 경우 return을 사용하고 =을 이용할 수 있습니다.

2023-07-10 13:37 UTC, kyucumber commented on src/main/kotlin/minesweeper/domain/MinesMap.kt
> +        }
```suggestion
        if (tile.isMine || tile.isOpen) {
            return
        }
```

2023-07-10 15:58 UTC, minhyukseul commented on src/test/kotlin/minesweeper/domain/MinesWeeperGameTest.kt
> +    "입력받은 위치는 높이와 넓이보다 작거나 같아야한다" {
아 저 구간을 저렇게 감싸면 되는거군요 감사합니다~

2023-07-10 16:02 UTC, minhyukseul commented on src/main/kotlin/minesweeper/MineSweeperGameMain.kt
> +    })
한수 배웠습니다. 감사합니다!

2023-07-15 15:09 UTC, kyucumber approved these changes
피드백 잘 반영해주셨네요.

마지막 미션까지 수고 많으셨습니다.

2023-07-15 15:09 UTC, merged