🚀 2단계 - 지뢰 찾기(지뢰 개수)
next-step/kotlin-minesweeper pull request #365
Opened 2023-11-25 08:11 UTC by AlbertImKr

형준 님 안녕하세요. 임 홍광입니다.
오랜만입니다. 
이번에도 잘 부탁드립니다. 
항상 건강하시길 바랍니다.

- 최대한 모든 원시 값과 문자열을 포장했습니다.
- 일급 컬렉션은 만약에 컬렉션 작업외 다른 기능도 있으면 그 컬렉션을 분리하고 있다.
   - 기존 코드에서 GameBoard의 List를 일급 객체로 분리하려고 했는데 실제로 아직 컬렉션 작업외의 기능이 존재하지 않아 분리 하지 않았습니다. 
   - 최종 코드는 일급 객체 mines를 사용했습니다.

2023-11-25 14:54 UTC, Flamme1004K requested changes
안녕하세요!

2단계 미션 고생하셨습니다!  몇 가지 체크하고 다음 단계로 넘어가고 싶어서 코멘트 남겼습니다.

코멘트 확인 후 코멘트 및 DM 부탁드립니다! 그 후 다시 리뷰 요청 부탁드릴게요!

감사합니다!

2023-11-25 14:54 UTC, Flamme1004K commented on src/main/kotlin/ConsoleUserInterface.kt
> +    }
저는 기존의 GameBoard가 List<CellGrid>의 일급 객체 역할을 한 것 같았는데, 현재는 제거하고 ConsloeUserInterface의 도메인 로직과 합쳐졌군요. 😶 저는 현재 view에 대한 부분도 이전과 같이 domain과 분리되었으면 좋은 것 같은데. 혹시 변화한 이유를 알 수 있을까요?

2023-11-25 14:54 UTC, Flamme1004K commented on src/main/kotlin/MineGenerator.kt
> +    fun generate(height: Int, width: Int, count: Int): Mines
일급 컬렉션 사용 👍

2023-11-25 14:54 UTC, Flamme1004K commented on src/main/kotlin/Mines.kt
> +    fun countMineAround(point: Point): Int = mineList.count { it.point.isAround(point) }
👍👍👍 획기적인 인접한 지뢰 카운터 로직이네요!

2023-11-25 14:54 UTC, Flamme1004K commented on src/test/kotlin/MinesTest.kt
> +    @ParameterizedTest
어디서 지뢰가 있는지에 대한 예시 너무 좋네요 👍👍

2023-11-25 14:54 UTC, Flamme1004K commented on src/main/kotlin/ConsoleUserInterface.kt
>  class ConsoleUserInterface : UserInterface {
현재 main/kotlin 패키지 안에 다 있는 것 같은데, 도메인과 뷰에 대한 패키지로 나눠보는 건 어떠실까요?

2023-11-25 14:54 UTC, Flamme1004K commented on README.md
> +- [ ] 지뢰의 개수를 포함한 보드를 만든다
😁

2023-11-25 22:15 UTC, AlbertImKr commented on src/main/kotlin/ConsoleUserInterface.kt
> +    }
맞습니다. GameBoard가 일급 객체라고 생각했습니다.
그리는 부분인 Console 출력할 때만 사용해서 view로 옮겼습니다.

2023-11-26 01:50 UTC, AlbertImKr commented
패키지 분리했습니다.

2023-11-26 10:33 UTC, Flamme1004K commented on src/main/kotlin/ConsoleUserInterface.kt
> +    }
답변 감사합니다 👍 

지뢰찾기 게임에 대해 지뢰에 집중할 수 있는 설계 좋네요. 👍

2023-11-26 10:33 UTC, Flamme1004K approved these changes
안녕하세요!

2단계 미션 고생하셨습니다! 머지하도록 하겠습니다.

다음 미션도 화이팅입니다!

2023-11-26 10:33 UTC, Flamme1004K commented on README.md
> +- [ ] 지뢰의 개수를 포함한 보드를 만든다
요건 나중에 체크해주세요~

2023-11-26 10:33 UTC, Flamme1004K commented on src/main/kotlin/MinesWeeper.kt
> +import business.MineGenerator
패키지 분리 👍👍👍

2023-11-26 10:34 UTC, merged