🚀 4단계 - 지뢰 찾기(리팩터링)
next-step/kotlin-minesweeper pull request #379
Opened 2023-11-29 16:45 UTC by AlbertImKr

형준 님 안녕하세요. 임 홍광입니다.

리뷰 요청드립니다.

좋은 하루 보내세요.

2023-11-30 12:53 UTC, Flamme1004K requested changes
안녕하세요!

4단계 미션 고생하셨습니다! 몇 가지 코멘트 남겼으니 확인 후 다시 리뷰 요청 부탁드립니다.

감사합니다.

2023-11-30 12:53 UTC, Flamme1004K commented on src/main/kotlin/business/Board.kt
> +    fun countMines(point: Point): Any = _cells.countMines(point)
테스트에 쓰이는 함수들이군요~ 저 같은 경우에는 테스트를 위한 함수는 피하고 있어요. 왜냐하면, 테스트를 위한 함수는 편의 메서드이기도 하고, 언제든지 깨진유리창이 될 수 있기 때문이에요. 홍광님은 테스트를 위한 함수를 어떻게 생각하시나요?

2023-11-30 12:53 UTC, Flamme1004K commented on src/main/kotlin/business/Cells.kt
> +    private val _cells: MutableList<MutableList<Cell>> = cells.map(List<Cell>::toMutableList).toMutableList()
MutableList<MutableList<Cell>> 를 좀 더 클래스로 나누어서 리팩토링 해볼까요?

2023-11-30 12:53 UTC, Flamme1004K commented on src/main/kotlin/business/Cells.kt
> +    fun copy(): Cells = Cells(_cells.map { it.map { cell: Cell -> cell } })
toList를 활용할 수 있지 않았을까하네요. 👀

2023-11-30 12:53 UTC, Flamme1004K commented on src/main/kotlin/business/Cells.kt
> +        .count { isMine(it) }
open 할 때 항상 만드는 쪽에서 이제 mine을 심었을 때 미리 만들어 보는 쪽으로 변경해 보는 건 어떨까요?

2023-11-30 12:53 UTC, Flamme1004K commented on src/main/kotlin/business/Cells.kt
> +        point.x in _cells.indices && point.y in _cells[FIRST_INDEX].indices
Cell에 point도 같이 있었다면, equals hashcode를 재정의하여 _cells 안에서 직접적으로 찾을 수도 있어 보이네요.

2023-12-01 00:31 UTC, AlbertImKr commented on src/main/kotlin/business/Board.kt
> +    fun countMines(point: Point): Any = _cells.countMines(point)
동의합니다. SornaLint 를 사용하고 있는데 테스트에만 쓰이는 함수인지 힌트를 주지 않는 것 같아요. 쉽게 확인 할 수 있는 방법이 있나요 ?

2023-12-01 12:16 UTC, AlbertImKr commented
형준 님 안녕하세요. 임 홍광입니다.

리뷰 반영 했습니다. 재리뷰 요청드립니다.

2023-12-01 13:25 UTC, Flamme1004K approved these changes
안녕하세요!

그동안 지뢰찾기 미션 너무나도 잘 해주셨습니다. 이만 머지하도록 하겠습니다.

앞으로의 성장 응원하겠습니다.

2023-12-01 13:25 UTC, merged