🚀 2단계 - 지뢰 찾기(지뢰 개수)
next-step/kotlin-minesweeper pull request #387
Opened 2023-12-01 15:23 UTC by Ho-Ya-Ho

안녕하세요 리뷰어님

step1 피드백 반영과 2단계 - 지뢰 찾기(지뢰 개수) 구현 완료하였습니다
확인부탁드리겠습니다😁

2023-12-02 14:42 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2023-12-02 14:42 UTC, kyucumber commented on src/main/kotlin/domain/GameBoard.kt
>      companion object {
로직이 전부 companion object로 구성되어 있네요. 

로직의 대부분이 static으로 구성되어 있는 경우 도메인에 대한 책임들이 클래스에 적절히 배치되기 어렵습니다. 이후에 개발하는 개발자들도 대부분 기존에 구성된 코드를 따라 static으로 정의하게 될 것이라서요.

꼭 필요하다고 생각되는 로직만 companion으로 구성하고 GameBoard와 같은 클래스가 가져야 할 책임은 무엇일지 고민해보시고 필요한 메서드는 추출해 적절한 클래스에 배치해보시면 좋겠습니다.

2023-12-02 14:42 UTC, kyucumber commented on src/main/kotlin/domain/GameBoard.kt
> +            val gameBoard = createNeighborMinesCount(boardSettings, board)
정상적으로 설정된 Board를 얻기 위해서는 아래 로직이 수행되어야 하네요.

1. 빈 게임 보드 생성
2. 초기화 메서드 호출
3. 주변 지뢰 개수 계산

호출 순서를 바꾸거나 호출을 누락하면 보드가 제대로 생성되지 않을 것 같은데 지금의 형태보다는 아래와 같이 한번에 모든 보드가 세팅된 형태로 제공할 수 있으면 좋지 않을까요?

```
GameBoard.from(boardSettings) // 이 메서드 호출 결과로 생성된 보드는 지뢰 및 주변 지뢰 개수가 모두 초기화되어 있다.
```

2023-12-02 14:42 UTC, kyucumber commented on src/main/kotlin/domain/Cell.kt
> +    fun createCell(boardSettings: BoardSettings, board: List<CellList>): Cell = Cell(point, cellInfo.createCellInfo(boardSettings, board, point))
createEmptyCell은 companion, 보드의 세팅을 받아 셀을 다시 생성하는 createCell 메서드는 클래스 내부에 메서드로 정의되어 있습니다.

두가지 모두 생성에 대한 부분인데 위치에 일관성이 없어 헷갈리는 것 같아요.

2023-12-02 14:42 UTC, kyucumber commented on src/main/kotlin/domain/Cell.kt
> +    fun createCell(boardSettings: BoardSettings, board: List<CellList>): Cell = Cell(point, cellInfo.createCellInfo(boardSettings, board, point))
다른 부분들도 동일하게 일관성이 없는 것 같은데 자기 자신의 상태를 바꾸는 것이 아니라 새로운 Cell을 생성하는 책임이 Cell에 있는 이런 형태가 내부 메서드에 정의되는게 맞을지 고민해보시면 좋겠습니다. 지금의 구현은 BoardSettings를 받는 부분이 상이하지만 create 보다는 데이터 클래스에서 제공하는 copy에 조금 더 가까운 느낌이에요.

2023-12-02 14:42 UTC, kyucumber commented on src/main/kotlin/domain/CellInfo.kt
> +        else { CellInfo(neighborMineCount = neighborMineCount.calculateNeighborMineCount(point, boardSettings, board)) }
지금 비어있는 보드를 만들고 지뢰 세팅 이후 CellInfo를 다 새로 교체하는 형태로 구성해주신 것 같은데요. 불변이 가지는 이점이 크지만 비어있는 블럭을 하나하나 설정한 다음에 교체하는 형태보다는 neighborMineCount만 가변으로 두고 메서드 호출을 통해 변경하는 것이 복잡도가 더 낮을 것 같다는 생각도 드네요.

한번 고민해보시면 좋겠습니다. 정답이 있는 것은 아니니 변경하실 필요는 없습니다.

2023-12-02 14:42 UTC, kyucumber commented on src/main/kotlin/domain/NeighborMineCount.kt
> +    fun calculateNeighborMineCount(point: Point, boardSettings: BoardSettings, board: List<CellList>): NeighborMineCount {
Cell이나 CellInfo가 가지는 책임이 현재 많지 않습니다. 인접한 지뢰 개수에 대한 계산 로직은 CellInfo나 Cell이 가져도 괜찮지 않을까요?

각각의 클래스들이 가지는 책임이 너무 적어서 과도하게 나누기보다는 NeighborMineCount는 음수가 아닌 것만 검증해도 충분하지 않을까 하는 생각이 듭니다.

2023-12-02 14:42 UTC, kyucumber commented on src/main/kotlin/domain/strategyImpl/RandomPointFactory.kt
> +    override fun createMinePoints(boardSettings: BoardSettings): List<Int> {
이 도메인에는 Point라는 클래스가 있습니다. createMinePoints가 `List<Point>`를 반환할 것이라 생각했는데 `List<Int>`를 반환하네요. 메서드 이름을 변경하거나 실제 메서드 이름에 맞게 `List<Point>`를 반환하는건 어떨까요?

2023-12-03 02:10 UTC, Ho-Ya-Ho commented on src/main/kotlin/domain/CellInfo.kt
> +        else { CellInfo(neighborMineCount = neighborMineCount.calculateNeighborMineCount(point, boardSettings, board)) }
좋은 의견이신 것 같습니다! 코멘트 감사합니다 ㅎㅎ😁

2023-12-03 03:33 UTC, Ho-Ya-Ho commented on src/main/kotlin/domain/GameBoard.kt
> +            val gameBoard = createNeighborMinesCount(boardSettings, board)
지금 현재도 gameBoard.createBoard() 를 호출하면 아래 요구사항이 만족될 것 같은데 혹시 이것을 말씀하신게 아니실까요? 아니라면 말씀 부탁드리겠습니다!!😁
`이 메서드 호출 결과로 생성된 보드는 지뢰 및 주변 지뢰 개수가 모두 초기화되어 있다.`

2023-12-03 03:37 UTC, Ho-Ya-Ho commented on src/main/kotlin/domain/Cell.kt
> +    fun createCell(boardSettings: BoardSettings, board: List<CellList>): Cell = Cell(point, cellInfo.createCellInfo(boardSettings, board, point))
companion object를 사용하지 않고 내부 메서드로 변경하였고 copy하는 action을 제거하고 변수명에 맞도록 create하도록 변경하였습니다!

2023-12-03 07:26 UTC, kyucumber requested changes
몇가지 코멘트 남겨두었으니 다음 단계 진행에 참고 부탁드립니다.

2023-12-03 07:26 UTC, kyucumber commented on src/main/kotlin/domain/GameBoard.kt
> +            val gameBoard = createNeighborMinesCount(boardSettings, board)
요건 제가 잘못 봤네요. controller쪽 보던게 이어지면서 컨트롤러에 정의된 메서드로 착각했습니다.

2023-12-03 07:26 UTC, kyucumber commented on src/main/kotlin/domain/GameBoard.kt
> +    fun from(boardSettings: BoardSettings, createPointStrategy: CreatePointStrategy): GameBoard {
from, of 등은 보통 정적 팩터리 메서드의 네이밍에 사용됩니다. 내부 메서드의 이름으로 사용하기엔 GameBoard라는 인스턴스가 생성된 이후에 호출될 것이므로 다소 어색하지 않나 하는 생각이 드네요.

2023-12-03 07:26 UTC, kyucumber commented on src/main/kotlin/controller/minesweeperController.kt
> +    return gameBoard.from(boardSettings, RandomPointFactory())
외부에서 빈 GameBoard 생성 이후 gameBoard.from을 다시 호출할 필요가 있을까요? 아래처럼 하는건 어떨까요?

```
return GameBoard(boardSettings, RandomPointFactory())
```

2023-12-03 07:26 UTC, kyucumber approved these changes
몇가지 코멘트 남겨두었으니 다음 단계 진행에 참고 부탁드립니다.

2023-12-03 07:26 UTC, merged