[step2] 지뢰 찾기(지뢰 개수)
next-step/kotlin-minesweeper pull request #41
Opened 2021-03-22 11:43 UTC by karian7

안녕하세요! 선호님. 2단계 리뷰 요청 드립니다.

[지난 PR](https://github.com/next-step/kotlin-minesweeper/pull/40) 에서 주신 피드백들에 댓글 달아 두었습니다 😀 
이번 구현에서 고려한 부분은 `Cell` 와 `MotherCell` 을 분리하여 `Cell` 불변객체로 만들고자 하였습니다.

그럼 리뷰 부탁드립니다~

2021-03-23 10:27 UTC, vsh123 requested changes
광수님 안녕하세요!!
깔끔한 커밋과 구조가 읽기 너무 좋았습니다 💯 

다만 새로 생성된 객체에 대해서 단위테스트가 존재하지 않는 것 같아요! 이를 추가해보면 어떨까요?
그리고 몇가지 코멘트를 드렸으니 한번 생각해보시면 좋을 것 같습니다!

2021-03-23 10:27 UTC, vsh123 commented on src/main/kotlin/minesweeper/domain/Matrix.kt
> +    fun around(index: Int): List<Int> {
해당 함수에 대한 테스트가 존재하지 않는 것 같아요! 테스트를 작성해보면 어떨까요?

2021-03-23 10:27 UTC, vsh123 commented on src/main/kotlin/minesweeper/domain/Matrix.kt
> +        return Around.apply(x, y)
apply라는 네이밍은 자기 Around를 리턴해야할 것 같은 느낌인데요! 네이밍을 조금 더 고려해보면 어떨까요?

2021-03-23 10:27 UTC, vsh123 commented on src/main/kotlin/minesweeper/domain/Position.kt
> +    fun valid(width: Int, height: Int): Boolean = !negative() && !outside(width, height)
negative()도 결국은 `outside()`를 검증하는 로직안에 포함된 개념이라고 생각하는데요! 하나로 합쳐보면 어떨까요?

2021-03-23 10:27 UTC, vsh123 commented on src/main/kotlin/minesweeper/domain/Position.kt
> +    override fun toString(): String {
toString을 재정의하신 이유가 있을까요?

2021-03-23 10:27 UTC, vsh123 commented on src/main/kotlin/minesweeper/domain/MotherCells.kt
> +    constructor(count: Int) : this(valuesOf(count))
Factory메서드를 만들고, 주생성자를 통해서 만들었다면 위임과 함께 `map,sorted`함수도 재정의가 필요없었을 것 같은데요!
혹시 지금과 같이 구현하신 다른 이유가 있을까요?

2021-03-23 10:27 UTC, vsh123 commented on src/main/kotlin/minesweeper/domain/MotherCells.kt
> +        private fun increaseCount(cells: List<MotherCell>) {
`List<MotherCell>`를 가지고 있는 일급컬렉션을 만들어도 괜찮을 거 같아요! 다만 현재 `MotherCells`와 네이밍이 겹칠 수 있겠군요..ㅠㅠㅠ

2021-03-23 10:27 UTC, vsh123 commented on src/main/kotlin/minesweeper/domain/Cells.kt
> +        require(cells.filter { it.bomb }.count() in 1 until size)
해당 validation에 대한 테스트도 있으면 좋겠네요! :)

2021-03-23 14:37 UTC, karian7 commented on src/main/kotlin/minesweeper/domain/Position.kt
> +    override fun toString(): String {
디버깅 할 때 좀 더 쉽게 보려고 넣었어요. 필요 없겠네요.

2021-03-23 14:46 UTC, karian7 commented on src/main/kotlin/minesweeper/domain/MotherCells.kt
> +        private fun increaseCount(cells: List<MotherCell>) {
다음 단계에서 좋은이름 생각해 볼께요 😉

2021-03-23 14:54 UTC, karian7 commented on src/main/kotlin/minesweeper/domain/Matrix.kt
> +    fun around(index: Int): List<Int> {
`Coordinate` 가 불필요해 보여서 제거하고 `Matrix` 를 직접 사용하게 변경했어요. 866651503bfeb323870b3726d6721371321edc70

2021-03-23 14:54 UTC, karian7 commented on src/main/kotlin/minesweeper/domain/Matrix.kt
> +        return Around.apply(x, y)
7540bc233fe1ab114158464712062ef88c159809 에서 반영하였습니다.

2021-03-23 14:54 UTC, karian7 commented on src/main/kotlin/minesweeper/domain/Position.kt
> +    fun valid(width: Int, height: Int): Boolean = !negative() && !outside(width, height)
f19ee10003ff975538f591cd53c31f2cc8c96d75 에서 반영했어요.

2021-03-23 14:55 UTC, karian7 commented on src/main/kotlin/minesweeper/domain/Cells.kt
> +        require(cells.filter { it.bomb }.count() in 1 until size)
추가했습니다. 😀 
83981a547d99a17e7cda75a52f36caf2853d9d12

2021-03-23 14:58 UTC, karian7 commented
선호님. 다음 단계를 이미 진행중이어서 각 댓글의 커밋아이디로 관련 변경커밋에 대한 댓글을 달아두었습니다.
괜찮으시다면 각 댓글의 커밋링크로 검토해 주시면 감사하겠습니다. 🙇

2021-03-24 12:30 UTC, vsh123 approved these changes
광수님 안녕하세요~!!
코멘트 드린 내용들은 링크로 확인 완료했습니다 :) 

다음단계를 위해서 이번 단계는 머지하도록 할게요!!
마지막까지 화이팅입니다!

2021-03-24 12:31 UTC, merged