[Step2] 2단계 - 지뢰 찾기(지뢰 개수)
next-step/kotlin-minesweeper pull request #430
Opened 2024-12-08 04:18 UTC by nooblette

안녕하세요! 2단계 미션 제출합니다.

구현 내용은 다음과 같습니다.
- 1단계 미션 리팩토링
  - 미사용 import 제거, 테스트 메서드 수정
  - 지난 미션에서 리뷰 주셨던 `MapTest`의 테스트 로직을 의도에 맞게 수정하였습니다. (행의 크기 > 열의 크기, 행의 크기 < 열의 크기, 행의 크기 = 열의 크기에 대해 테스트)
- 2단계 미션 구현
  - 주위에 위치한 지뢰의 개수 count 로직 추가

2단계 미션도 잘 부탁드립니다. 감사합니다.

2024-12-08 15:01 UTC, pci2676 requested changes
조금 더 개선해보면 좋을 부분에 리뷰를 남겨두었으니 확인해주시고 한번 더 요청 부탁드리겠습니다. 😄

2024-12-08 15:01 UTC, pci2676 commented on src/main/kotlin/console/MineSweeperConsole.kt
> +        var map = Map.create(height = height, width = width)
지난 리뷰에 남기지 못한 부분을 발견하여 이곳에 남깁니다~

height와 width의 경우 단일 값을 나타내는 객체로 보입니다.

이러한 경우 인라인 클래스를 이용하여 표현하는 방법이 있으니 참고해주세요!

https://kotlinlang.org/docs/inline-classes.html

2024-12-08 15:01 UTC, pci2676 commented on src/main/kotlin/map/Rows.kt
> +    fun updateMineCounts(): Rows = Rows(rows.map { it.updateMineCounts(rows = this) })
Rows <-> Columns 간의 양방향 의존관계가 성립되고 있는것 같습니다.

이러한 의존관계 없이 문제를 해결해 볼 수 있으면 더욱 좋을것 같습니다. 😄

2024-12-08 15:01 UTC, pci2676 commented on src/main/kotlin/map/Point.kt
> +    fun updateMineCounts(rows: Rows): Point {
중요한 도메인 로직으로 보입니다! 그러나 테스트 코드가 존재하지 않아 코드만 보고 어떻게 동작하는지 파악해야하는 부분이 조금 아쉬운것 같습니다.

테스트 코드를 추가해주시면 좋을것 같습니다 😄

2024-12-08 15:01 UTC, pci2676 commented on src/main/kotlin/cell/Cell.kt
> +        private const val DEFAULT = "C"
view와 밀접하게 연관된 값 같습니다.

그리고 Cell은 point가 의존하고 있는 대상으로 보입니다.

domain 영역 내에 위치한 객체들은 view에 의존하지 않도록 작성해보시면 좋을것 같습니다.

view의 요구사항이 변경되었을때는 view에 대한 코드만 변경하는 것이 좋은데 domain이 view에 의존하다보면 domain 내의 다른 코드들도 함께 변경해야하는 상황이 발생할 수 있습니다. 😄

2024-12-08 15:01 UTC, pci2676 commented on src/main/kotlin/map/Point.kt
> +    val point: Pair<Index?, Index?>,
[질문] Cell 또한 point의 속성을 가지고 있는 객체로 바라보는거에 대해서는 어떻게 생각하시나요? 일종의 상태패턴을 적용해볼 수 있지 않을까 라는 생각에 질문을 드려봅니다 😄

2024-12-08 15:01 UTC, pci2676 commented on src/main/kotlin/console/MineSweeperConsole.kt
> +        map = map.updateMineCountByCell()
`Map` -> `grid` -> `point(Rows)` -> `rows(List<Columns>)` ->  `row(Row)`

이 과정을 수행하기 위해 꽤 많은 여정을 거쳐야 하는것으로 보입니다~

객체탐색은 도메인 로직을 구현함에 있어 필수적인 부분이지만 그 깊이가 깊어짐에 따라 피로도가 쌓이기 마련인데요.

이러한 객체탐색의 깊이를 줄여보는 시도를 해보시는것도 한번쯤 도전해볼만한 요소로 생각합니다.

지금 계속해서 List를 활용하여 객체탐색을 이어가는데 다른 자료구조(ex. Map)를 사용해보는건 어떨까요?

어떠한 자료구조를 선택하느냐에 정답은 없기 때문에 반드시 개선을 바라고 드리는 리뷰는 아니니 한번 쯤 생각만 해주셔도 좋을것 같습니 다. 😄

2024-12-08 15:01 UTC, pci2676 commented on src/main/kotlin/map/Map.kt
> +    fun updateMineCountByCell(): Map = Map(grid = Grid(grid.points.updateMineCounts()))
Map이 grid가 points를 아는것과 points의 updateMineCounts()를 호출한다는 것까지 반드시 알아야할까요?

디미터 법칙을 적용해서 Map은 grid에게만 명령을 내리고 grid 내에서 다른 행동을 호출하도록 위임하는건 어떨까요?

grid라는 객체로 rows를 추상화해두었는데 Map에서 그 추상화의 구체적인 사항이 드러나버리는것 같습니다.

이 부분뿐 아니라 다른 부분도 동일한 부분이 있으니 한번 고려해주세요 😄

2024-12-09 13:00 UTC, nooblette commented on src/main/kotlin/console/MineSweeperConsole.kt
> +        var map = Map.create(height = height, width = width)
코틀린에서는 Wrapping 클래스로 인한 성능저하까지 고려하고 언어 차원에서 제공하는 방안이 있나보네요 🤔 
미처 몰랐던 부분인데 리뷰주셔서 감사합니다 :smile: 덕분에 유용한 내용을 알 수 있있어요!

```kotlin
@JvmInline
value class Height(
    val size: Int,
) {
    init {
        require(size >= 0) { "높이는 음수일 수 없습니다." }
    }
}

```

리뷰 주신대로 수정하였습니다 👍

2024-12-09 13:06 UTC, nooblette commented on src/main/kotlin/map/Rows.kt
> +    fun updateMineCounts(): Rows = Rows(rows.map { it.updateMineCounts(rows = this) })
`Rows`를 넘기는 것 대신 함수를 전달하도록 수정하면서 의존성이 단방향으로 흐르도록 수정했습니다.
또한 이 과정에서 아래에서 리뷰주신 디미터 법칙 내용을 적용하면서 객체간 책임을 명확히 분리하였습니다.

지뢰의 상태 값 업데이트 전략에 대한 책임을 갖는 `MineCountStrategy` 인터페이스를 도입했고, 
이에 따라 다음과 같이 함수를 전달하도록 수정했는데, 객체지향적인 설계를 유지하면서 코틀린의 함수형 프로그래밍 특성도 살릴 수 있었던 것 같아요 :smile:

```kotlin
    fun updateMineCountByCell(): Grid {
        val updateRows =
            points.updateMineCount { rowIndex, columnIndex -> mineCountStrategy.calculate(rowIndex, columnIndex) }

        return Grid(points = updateRows, mineCountStrategy = mineCountStrategy)
    }
```

의존관계 해결 방안을 생각하면서 덕분에 많은 고민을 할 수 있었습니다. 감사합니다 :+1:

2024-12-09 13:07 UTC, nooblette commented on src/main/kotlin/map/Point.kt
> +    fun updateMineCounts(rows: Rows): Point {
`SurroundingMinesTest`와 `PointTest` 추가하였습니다 :+1:

2024-12-09 13:07 UTC, nooblette commented on src/main/kotlin/cell/Cell.kt
> +        private const val DEFAULT = "C"
제거했습니다! 유익한 인사이트 주셔서 감사합니다 :smile:

2024-12-09 13:08 UTC, nooblette commented on src/main/kotlin/map/Point.kt
> +    val point: Pair<Index?, Index?>,
다음과 같이 Cell의 상태를 나타내는 `CellStatus` 인터페이스와 상태별 구현 클래스를 도입했습니다.
다만 상태 패턴에 대한 지식과 경험이 부족해서, 적절하게 적용했는지 모르겠네요 😅 제가 이해한 내용이 맞는 의견 부탁드립니다.

```kotlin
data class Cell(
    override val value: String? = null,
    override val status: CellStatus = EmptyCell,
) : Element  { ... }

interface CellStatus {
    fun isMine(): Boolean = false
}

object EmptyCell : CellStatus

```

2024-12-09 13:13 UTC, nooblette commented on src/main/kotlin/console/MineSweeperConsole.kt
> +        map = map.updateMineCountByCell()
지금처럼 `Map`과 각 행, 열별 객체 `Rows`와 `Columns` 클래스를 도입하다보면 설계가 복잡해지는건 어쩔 수 없는 부분일 것 같아요 🤔 (물론 말씀주신대로 객체 탐색 깊이를 줄이는 것도 고민해볼만한 문제라고 생각합니다.)

다만 지뢰찾기 이번 미션을 구현하면서 각 Cell의 상태 값을 업데이트하는건 좌표와 좌표 값에 대한 상태를 갖고있는 `Point` 객체가 수행해야한다고 생각했습니다.

데이터 처리 방안인 `countMines` 함수도 결국 이 `Point` 객체에서 수행하려고 하다보니 자연스레 객체 탐색의 깊이도 깊어진 것 같아요. 그리고 다른 자료구조를 사용한다고 하더라도 이러한 문제를 완벽히 해결할 수는 없을 거라고 생각하는데, 관련해서 찬인님 의견은 어떠실까요?

2024-12-09 16:47 UTC, pci2676 commented on src/main/kotlin/map/Point.kt
> +    val point: Pair<Index?, Index?>,
저는 별도의 Cell을 상속하는 별도의 클래스들이 status의 역할을 대신하는 구조를 생각했습니다~

Cell().updateValue() -> return EmptyCell() or NumberCell() or MineCell()

```kotlin
class EmptyCell: Cell

class NumberCell: Cell

class MineCell: Cell 
```

2024-12-09 17:15 UTC, pci2676 commented on src/main/kotlin/console/MineSweeperConsole.kt
> +        map = map.updateMineCountByCell()
> 다만 지뢰찾기 이번 미션을 구현하면서 각 Cell의 상태 값을 업데이트하는건 좌표와 좌표 값에 대한 상태를 갖고있는 Point 객체가 수행해야한다고 생각했습니다.
>
> 데이터 처리 방안인 countMines 함수도 결국 이 Point 객체에서 수행하려고 하다보니 자연스레 객체 탐색의 깊이도 깊어진 것 같아요. 그리고 다른 자료구조를 사용한다고 하더라도 이러한 문제를 완벽히 해결할 수는 없을 거라고 생각하는데, 관련해서 찬인님 의견은 어떠실까요?

사실 이 리뷰는 한번 고민만 해봐주십사 하고 남긴거라서요 ㅎㅎ

저였다면 어떻게 했을까?를 질문하신거라면 저는 point는 위치정보에 대한 것만 다루도록 하고 이외의 정보는 다른 객체에 위임했을것 같습니다.

`Map<Point, Element>` 와 같은 형태가 Grid가 되지 않았을까 싶네요~

2024-12-09 17:15 UTC, pci2676 approved these changes
다음단계를 진행해주세요.

merge 하겠습니다. 🚀

2024-12-09 17:15 UTC, merged