[Step3] 지뢰 찾기(게임 실행)
next-step/kotlin-minesweeper pull request #431
Opened 2024-12-08 11:42 UTC by SeongminKimKR

안녕하세요~ 수현님 😄 
지난 스텝에서 피드백 사항 및 이번 스텝 요구사항 반영해보았습니다.
리뷰 잘 부탁드리겠습니다 🙇

2024-12-09 08:24 UTC, wisemuji requested changes
안녕하세요 성민님!

3단계도 구현 잘 해주셨습니다 💯  깔끔한 구현이 좋았습니다
몇 가지 고민해보시면 좋을만한 코멘트를 달았으니 확인해주시면 감사하겠습니다.

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요!

2024-12-09 08:24 UTC, wisemuji commented on src/test/kotlin/minesweeper/domain/BoardTest.kt
> +class BoardTest : BehaviorSpec({
BehaviorSpec을 잘 활용해주셨네요! 🙇

2024-12-09 08:24 UTC, wisemuji commented on src/main/kotlin/minesweeper/domain/Board.kt
> +    fun open(pointInput: Pair<Int, Int>): List<Land> {
다른 개발자들도 `Pair<Int, Int>`가 무엇을 의미하는지 이해할 수 있을까요?

2024-12-09 08:24 UTC, wisemuji commented on README.md
일부 프로그래밍 요구 사항 반영이 누락된 것 같아요!

> 모든 원시 값과 문자열을 포장한다.

2024-12-09 08:24 UTC, wisemuji commented on src/main/kotlin/minesweeper/domain/Board.kt
현재는 Board가 가지고 있는 함수(==기능)이 다소 많은데요,

> 프로그래밍 요구 사항: 모든 엔티티를 작게 유지한다.

다른 객체에게 일부 역할과 책임을 위임해볼 수 없을까요?

예를 들어,
- `Land`에게 지뢰 주변 계산 로직 위임
- `Land`스스로 자신이 열렸는지 여부를 들고 있음

등의 아이디어가 있을 것 같아요. 어떻게 생각하시나용?

2024-12-09 08:24 UTC, wisemuji commented on src/main/kotlin/minesweeper/domain/Board.kt
> +        val openedLands = mutableListOf<Land>()
많은 코틀린의 타입은 불변이 기본값이고 List도 그중 하나입니다. 이런 불변 타입을 사용하는 것의 장점을 온전히 누리기 위해 전 코틀린에서는 가능하면 var이나 Mutable 타입 사용을 지양하려고 하고 있습니다. :slightly_smiling_face:

Kotlin Collection API을 활용하면 MutableList 선언 없이도 구현 가능해보여요. 이 상황에서는 map을 활용해볼 수 있겠네요 🙂

2024-12-09 08:24 UTC, wisemuji commented on src/main/kotlin/minesweeper/domain/point/Mines.kt
> +    operator fun contains(mine: Mine): Boolean = placedMines.contains(mine)
operator overloading 👍

2024-12-09 09:19 UTC, SeongminKimKR commented on src/main/kotlin/minesweeper/domain/Board.kt
맞아요.. 말씀해주신대로 Board가 좀 거대해지고 있는 것 같습니다!
다른 객체에게 책임을 위임해보겠습니다 👍

2024-12-09 09:21 UTC, SeongminKimKR commented on src/main/kotlin/minesweeper/domain/Board.kt
> +    fun open(pointInput: Pair<Int, Int>): List<Land> {
음.. 아니요..! 한눈에 파악하기 어려울 것 같네요.
다른 파라미터를 써서 의미가 드러나게 수정해볼게요! 👍

2024-12-09 09:23 UTC, SeongminKimKR commented on README.md
엇 그렇군요! 확인해보겠습니다 👍 
꼼꼼한 피드백 감사합니다 🙇

2024-12-10 01:56 UTC, wisemuji approved these changes
안녕하세요 성민님, 리뷰 반영 넘 잘 해주셨습니다 👍 

남겨드린 코멘트는 다음 단계 진행해주시면서 같이 반영해주시면 됩니다!
지금까지 구조를 넘 잘 설계해주셔서 다음 단계도 수월하게 구현하실 것 같네요 ㅎㅎ

지뢰찾기 마지막 단계도 화이팅입니다 💪

2024-12-10 01:56 UTC, wisemuji commented on src/main/kotlin/minesweeper/domain/Board.kt
>          }
Direction의 entries를 꺼내어(get) 조작하는 것이 아니라,
Direction 그 자체에게 메세지를 보내보면 어떨까요~?

2024-12-10 01:56 UTC, wisemuji commented on src/main/kotlin/minesweeper/domain/point/Land.kt
>  ) : Point(r, c) {
좋습니다 👍 

Board가 너무 비대해지지 않고, Land에게 적절히 역할과 책임이 위임되었네요!

테스트 시나리오도 잘 챙겨주셨네요.

2024-12-10 01:56 UTC, wisemuji commented on src/main/kotlin/minesweeper/domain/point/Land.kt
>  ) : Point(r, c) {
다음 요구 사항도 같이 챙겨주시면 좋을 것 같아요!

> 줄여 쓰지 않는다(축약 금지).

2024-12-10 01:56 UTC, wisemuji commented on src/main/kotlin/minesweeper/domain/Board.kt
>          }
메세지를 던지는 과정에 같이 읽어보시면 도움되실 글도 같이 첨부합니다 🙂 

[창시자 앨런 케이가 말하는, 객체 지향 프로그래밍의 본질](https://velog.io/@eddy_song/alan-kay-OOP)
[객체 지향 프로그래밍과 메시징](https://homoefficio.github.io/2019/07/04/%EA%B0%9D%EC%B2%B4-%EC%A7%80%ED%96%A5-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D%EA%B3%BC-%EB%A9%94%EC%8B%9C%EC%A7%95/)

2024-12-10 01:56 UTC, merged