[Step3] 🚀 3단계 - 지뢰 찾기(게임 실행)
next-step/kotlin-minesweeper pull request #439
Opened 2024-12-11 15:08 UTC by kyuwon53

안녕하세요! 경록님 🚀 

피드백 반영과 3단계 지뢰 찾기(게임 실행) 미션 리뷰 요청드립니다! 
이번 미션도 잘 부탁드립니다 😄

2024-12-12 08:01 UTC, Rok93 requested changes
규원님 3단계도 빠르게 잘 진행해주셨습니다. 👍👍 
몇몇 코멘트 남겨두었으니 확인해서 반영 부탁드릴게요! 😃

이미 잘 지켜주셨지만 지뢰찾기 3단계 미션에서는 `객체지향 생활 체조 원칙`을 지켜서 코딩하라는 요구사항이 있습니다! 혹시나 제가 리뷰하면서 놓친부분이있을 수 있으니, 수정하시면서 한번 더 확인 부탁드릴게요. 😉

2024-12-12 08:01 UTC, Rok93 commented on src/main/kotlin/minesweeper/app/Minesweeper.kt
> +                }
게임을 계속 진행할지 말지를 `mineField` 객체에게 메시지로 물어서 게임을 계속 진행할지 말지를 결정할 수는 없을까요? 😃

2024-12-12 08:01 UTC, Rok93 commented on src/main/kotlin/minesweeper/app/Minesweeper.kt
> +            isGameCleared(mineField) -> Action.GAME_CLEARED
잘 이해를 못했는데, `GAME_CLEARED` 는 어떤 케이스인걸까요? 🤔
----

아..! 게임 클리어!  이런 느낌이었군요? 😃

2024-12-12 08:01 UTC, Rok93 commented on src/main/kotlin/minesweeper/converter/MineFieldConverter.kt
> +        } else {
아래의 `객체지향 생활 체조 원칙`에 따라  else 구문을 제거해보면 어떨까요? 😃
> else 예약어를 쓰지 않는다.

2024-12-12 08:01 UTC, Rok93 commented on src/test/kotlin/minesweeper/entity/MineFieldTest.kt
> +                        }
저는 테스트 코드에서는 가급적 if-else 로직을 넣지 않는 것이 좋다고 생각하는데요. 
맥락이 조금 다를 수는 있지만, 아래의 글을 참고해보시면 좋을 것 같습니다. 😃

[조건부 (if~else) 로직 테스트코드에서 사용하지 않기](https://jojoldu.tistory.com/642)

2024-12-12 08:01 UTC, Rok93 commented on src/main/kotlin/minesweeper/entity/Coordinate.kt
> +                Coordinate(x + direction.deltaX, y + direction.deltaY)
`this.move(direction)` 와 같이 coordinate 객체에게 메시지를 보내볼 수 있을 것 같아요. 😃

2024-12-12 08:01 UTC, Rok93 commented on src/main/kotlin/minesweeper/app/Minesweeper.kt
> +    private fun handlePlayerAction(
`handlePlayerAction` 그리고 내부에서 호출하는 isGameOver, isGameCleared  동작들은 도메인 객체들에게 적절히 역할을 위임해볼 수 있을 것 같아요!

2024-12-12 12:12 UTC, kyuwon53 commented on src/main/kotlin/minesweeper/app/Minesweeper.kt
> +            isGameCleared(mineField) -> Action.GAME_CLEARED
네 맞습니다! 지뢰를 모두 찾지 못하고 지뢰를 선택했을땐 게임오버
지뢰가 아닌 셀을 모두 찾은 경우 게임 클리어! (통과) 입니다

2024-12-12 13:40 UTC, kyuwon53 commented
꼼꼼한 리뷰 감사합니다. 💯 👍 😄 
주신 피드백 반영했습니다!

2024-12-13 09:30 UTC, Rok93 requested changes
규원님 피드백 반영 잘해주셨네요! 👍💯
몇몇 코멘트 남겨두었는데, 확인해서 반영 부탁드릴게요. 🙏
잘 이해가 안되거나 어려운부분있으면 언제든지 DM 주세요. 😉

2024-12-13 09:30 UTC, Rok93 commented on src/main/kotlin/minesweeper/entity/MineField.kt
> +        val cell = findCell(coordinate)
아래와 같이 _cells 프로퍼티로부터 바로 findCell해도 됐을 것 같은데, 따로 메서드로 추출하신 이유가 있으실까요? 🤔
개인적으로는 조금 불필요한 메서드 추출로 보여서요

```suggestion
        val cell = _cells.findCell(coordinate)
```

2024-12-13 09:30 UTC, Rok93 commented on src/main/kotlin/minesweeper/entity/MineField.kt
> +    fun open(coordinate: Coordinate) {
조금 극단적인 케이스로 테스트해보기는했지만... 
아래의 요구사항을 만족하려면 수정이 필요할 것 같습니다. 
> 지뢰가 없는 인접한 칸이 모두 열리게 된다.

<img width="717" alt="image" src="https://github.com/user-attachments/assets/bf0ad1e8-57fe-465a-943e-b09c9d582dc2" />

2024-12-13 09:30 UTC, Rok93 commented on src/main/kotlin/minesweeper/entity/MineField.kt
> +        return cell is Cell.Empty && countAroundMines(coordinate) == 0
`0`이 어떤 의미를 가지는지 상수로 추출하여 네이밍으로 의도를 드러내주시면 좋을 것 같습니다. 😃

2024-12-13 09:30 UTC, Rok93 commented on src/main/kotlin/minesweeper/entity/MineField.kt
> +    }
다음 Action을 확인하는게 특정 `coordinate`와 연관이 있는걸까요? 
사실 모든 cell을 다 확인하여야하지 않을까 싶은데요.  (CLEARED 조건은 이미 전부 확인하고있군요 👀)

예를들어  1,1 위치의 지뢰를 open했지만,  `determinAction(Coordinate(1, 0)`을 하게된다면 Action`.CONTINUE` 가 될 수 있겠네요.  (사실 open과도 상관이 없이 특정 cell이 Mine이라면  GAME_OVER 가 되겠군요 🤔)


특정 cell이 Mine인지 확인하는게 아니라 open된 cell 중에 Mine이 있는지 여부를 확인하도록 변경이 필요해보입니다. 😁

2024-12-13 09:30 UTC, Rok93 commented on src/main/kotlin/minesweeper/entity/MineField.kt
> +            .filterIsInstance<Cell.Empty>()
가급적 인스턴스의 타입을 직접 확인하기보다는 cell에 메시지를 보내는 방식으로 Mine, Empty 필터링을 해보면 어떨까요? 😃

2024-12-13 09:30 UTC, Rok93 commented on src/main/kotlin/minesweeper/entity/MineField.kt
> +    private fun openAdjacentEmptyCells(coordinate: Coordinate) {
메서드의 위치를 적절히 두는 것도 코드를 파악하는데 도움이 많이 된다고 생각하는데요. 
저는 개인적으로 메서드가 호출되는 순서대로있는 것이 가장 가독성이 좋다고 생각하는 편입니다. 😃


현재 openAdjacentEmptyCells 메서드는 `open`에서 사용되는 메서드이고, open은 내부적으로 1. shouldOpenAdjacentCells 호출 뒤, openAdjacentEmptyCells를 호출하고있네요. 

이런 호출 순서대로 위치시킨다면 코드 파악이 한결 더 쉬워질 것 같습니다. 😉

2024-12-13 09:30 UTC, Rok93 commented on src/main/kotlin/minesweeper/entity/MineField.kt
> +        if (shouldOpenAdjacentCells(cell, coordinate)) {
생각해보니 어짜피 coordinate는 cell.coordinate와 동일할 것 같은데, shouldOpenAdjacentCells 메서드의 파라미터로 cell만 받아도 충분하지 않을까요? 
```suggestion
        if (shouldOpenAdjacentCells(cell, coordinate)) {
```

2024-12-13 09:30 UTC, Rok93 commented on src/main/kotlin/minesweeper/entity/MineField.kt
> +                if (cell is Cell.Empty && countAroundMines(cell.coordinate) == 0) {
위에서 아래와 같은 코멘트를 남겼었는데요! 
> 생각해보니 어짜피 coordinate는 cell.coordinate와 동일할 것 같은데, shouldOpenAdjacentCells 메서드의 파라미터로 cell만 받아도 충분하지 않을까요?

이 코멘트대로 shouldOpenAdjacentCells 메서드의 파라미터가 수정된다면 이걸 재활용해볼 수 있을 것 같아요. 

```suggestion
                if (shouldOpenAdjacentCells(cell)) {
```

2024-12-13 11:33 UTC, kyuwon53 commented on src/main/kotlin/minesweeper/entity/MineField.kt
> +        val cell = findCell(coordinate)
MineFieldConverter에서 해당 메서드를 쓰고 있습니다! 
내부에서는 추출한 메서드를 쓸 필요는 없겠네요

2024-12-13 11:41 UTC, kyuwon53 commented on src/main/kotlin/minesweeper/entity/MineField.kt
> +    private fun openAdjacentEmptyCells(coordinate: Coordinate) {
private 함수와 public 함수 상관없이 호출 순서대로 위치시키시나요? 
요게 항상 고민인거 같습니다 🤔

2024-12-13 11:43 UTC, kyuwon53 commented on src/main/kotlin/minesweeper/entity/MineField.kt
> +        if (shouldOpenAdjacentCells(cell, coordinate)) {
오! 아! 그렇네요! 감사합니다. 👍

2024-12-13 13:46 UTC, kyuwon53 commented on src/main/kotlin/minesweeper/entity/MineField.kt
> +    fun open(coordinate: Coordinate) {
열리는 기준이 헷갈려서 실제 지뢰  게임을 여러번 해봤습니다 . 최소 크기가 8*8이어서 8*8로 만들고 지뢰를 1으로 했는데 최소 기준이 8인 이유가 위와 같은 상황이 나와서가 아닐까라는 생각이 들었습니다. 정확히 구체적으로 어떻게 동작하는 건지를 모르겠어서 좀 더 알아보겠습니다. 🥲 

<img width="362" alt="스크린샷 2024-12-13 오후 9 35 42" src="https://github.com/user-attachments/assets/190644be-4a3b-4311-b233-caec787ca904" />
<img width="344" alt="스크린샷 2024-12-13 오후 9 35 49" src="https://github.com/user-attachments/assets/32dd7fc3-325d-4fc6-a90e-d5015f66dba2" />
<img width="350" alt="스크린샷 2024-12-13 오후 9 35 54" src="https://github.com/user-attachments/assets/568c32eb-8312-4301-8bf2-4d2a2ea7411e" />
<img width="346" alt="스크린샷 2024-12-13 오후 9 37 23" src="https://github.com/user-attachments/assets/9e0dfb38-6936-4aee-9e28-12dbc073f90f" />
<img width="367" alt="스크린샷 2024-12-13 오후 9 37 50" src="https://github.com/user-attachments/assets/157b72da-ef37-4198-be8f-2b254362f563" />

2024-12-14 11:51 UTC, Rok93 commented on src/main/kotlin/minesweeper/entity/MineField.kt
> +    private fun openAdjacentEmptyCells(coordinate: Coordinate) {
정답이 없는 영역이라 저는 이렇게 하고있다 정도로만 생각해주세요 : ) 

public과 private 메서드 중에 굳이 우열을 가리자면 당연히 public이라고 생각하지만 그렇다고 모든 public 메서드를 상단에 두지는 않고있어요. 

public a 메서드에서 b, c private 메서드를 호출하고있다면,   `a > b > c` 의 순서로 메서드를 위치시키고  새로운 public d 메서드는 c 다음에 위치시키는 방식으로 평소에는 관리하고 클래스 내부에 메서드가 너무 많은 경우에는 다른 객체와 협력하는 공개 메서드를 우선적으로 위에 두고, private 함수를 내리게 되는 것 같습니다. 😃

2024-12-14 12:28 UTC, Rok93 approved these changes
규원님 피드백 반영 잘해주셨습니다! 👍💯
3단계는 이정도면 충분한 것 같아서 이만 머지하도록하겠습니다. 👍👍 
4단계에서 뵙겠습니다. 🤗

2024-12-14 12:28 UTC, Rok93 commented on src/main/kotlin/minesweeper/entity/MineField.kt
> +            .filter { it.isWithinBounds(width, height) && !_cells.findCell(it).isRevealed }
이 filter부분이 개인적으로 조금 아쉽다고 생각이 드는데요. 🤔
`cells` 객체에게  특정 `coordinate`의 `adjacentCoordinates`를 찾아줘! 라고 메시지를 보내면 
조금 더 깔끔해지지 않을까요? 

```suggestion
        _cells. adjacentCoordinates(coordinate)
            .filter { !it.isRevealed }
```

지금 생각해보니 adjacentCoordinates 메서드의[네이밍](https://tecoble.techcourse.co.kr/post/2020-04-26-Method-Naming/)이 행위를 드러내주지 못하는 것 같은데, 동사구 네이밍으로 변경해보면 어떨까요? 🤗

2024-12-14 12:28 UTC, Rok93 commented on src/main/kotlin/minesweeper/entity/MineField.kt
> +    fun open(coordinate: Coordinate) {
아... 저도 잠시 이 동작 방식이 헷갈렸었네요 😅 

규원님이 구현하신 방식이 맞았어요!
헷갈리게해드려 죄송해요. 🙏

2024-12-14 12:28 UTC, Rok93 commented on src/main/kotlin/minesweeper/entity/MineField.kt
> +            openAdjacentEmptyCells(coordinate)
재귀함수의 장점은 간단하게 코드를 구현할 수 있어 깔끔하고 읽기 쉽다는 장점이 있지만 
반면에 너무 많은 호출이 누적되게된다면 Stack Over Flow가 발생할 수 있다는 문제점이 있는데요. 

코틀린에서 제공하는 [tailerec 키워드](https://1-three.tistory.com/137)을 사용하면 이 문제점을 개선해볼 수 있을 것 같습니다. 😃

2024-12-14 12:28 UTC, merged