Step3 - 지뢰찾기(게임실행)
next-step/kotlin-minesweeper pull request #485
Opened 2024-12-22 12:37 UTC by janghomoon

안녕하세요 PR 요청드립니다. 
빠른피드백 주셔서 감사합니다.

2024-12-23 04:02 UTC, janghomoon commented
안녕하세요  범준님 3단계 진행시 반영 요청 하셨던 부분중에 제가 깜빡하고  누락된 부분이 있네요ㅠㅠ
이번에   피드백주시면  피드백 주신거에 이전에 반영 요청 하셨던 부분까지 같이 하겠습니다.

2024-12-23 09:14 UTC, ddaaac requested changes
안녕하세요 장호님 👋 

구현 잘 해주셨습니다.

몇 가지 코멘트 남겼으니 확인해주세요.

2024-12-23 09:14 UTC, ddaaac commented on src/main/kotlin/mine/controller/MineController.kt
> +                isRunning = false
취향 차이가 있겠지만 저는 while(true) + return 방식을 선호합니다.
어디서 루프가 끝나는지 분명하게 알 수 있기 때문이에요.
장호님은 어떠신가요?

2024-12-23 09:14 UTC, ddaaac commented on src/main/kotlin/mine/controller/MineController.kt
> +                OutputView.gameEnd()
지뢰가 아닌 칸이 모두 열렸다면 다른 결과가 나와야하지 않을까요?

2024-12-23 09:14 UTC, ddaaac commented on src/main/kotlin/mine/domain/BoardCalculator.kt
> +        }
MineSweeper는 내부에 List<MineRow>를 갖고 있는 객체입니다.
지금은 MineSweeper에서 이 컬렉션을 "꺼내서" 다른 객체인 BoardCalculator에게 넘겨서 계산이 이뤄지고 있어요.
대신 [MineSweeper에게 메세지를 보내보는건](https://tecoble.techcourse.co.kr/post/2020-04-28-ask-instead-of-getter/) 어떨까요?

2024-12-23 09:14 UTC, ddaaac commented on src/main/kotlin/mine/domain/BoardCalculator.kt
> +            cell !is MineCell.MINE || cell.isOpen
여기도 마찬가지로 row에서 값을 꺼내지 말고 row에게 메세지를 던져봐도 좋을 것 같아요.

2024-12-23 09:14 UTC, ddaaac commented on src/main/kotlin/mine/domain/BoardCalculator.kt
> +        println("rowInRange: $rowInRange, colInRange: $colInRange")
디버깅을 위한 코드가 남아있는 것 같아요.

2024-12-23 09:14 UTC, ddaaac commented on src/main/kotlin/mine/domain/BoardCalculator.kt
> +            updateCell(coordinate, rowIndex, colIndex, cell)
여기도 위와 동일한 코멘트를 적용해볼 수 있을 것 같아요.
저는 메서드의 파라미터가 3개가 넘어가면 파라미터를 줄일 수 없을까?라는 생각이 들더라구요.
row.openCell()과 같은 메서드가 있다면 객체에 메세지를 던지며 파라미터 숫자를 줄일 수 있겠죠.

2024-12-23 09:14 UTC, ddaaac commented on src/main/kotlin/mine/dto/Coordinate.kt
> +class Coordinate(val x: Int, val y: Int)
단순 좌표만을 위한 클래스라 data class로 만들어도 좋을 것 같습니다!

2024-12-23 09:14 UTC, ddaaac commented on src/main/kotlin/mine/enums/MineCell.kt
> +sealed class MineCell(var isOpen: Boolean = false) {
외부에서 클래스 내부의 변수를 변경하게 되면 코드 예측이 어려워집니다.
내부에서만 변경 가능하게 구현해보면 좋을 것 같아요!

2024-12-23 09:14 UTC, ddaaac commented on src/main/kotlin/mine/enums/MineCell.kt
> +        override fun withOpen(isOpen: Boolean): MineCell = copy().apply { this.isOpen = isOpen }
```suggestion
        override fun withOpen(isOpen: Boolean): MineCell = copy(isOpen = isOpen)
```

도 가능합니다.

2024-12-23 09:14 UTC, ddaaac commented on src/test/kotlin/mine/domain/BoardCalculatorTest.kt
> +                MineRow(listOf(MineCell.MINE, MineCell.Number(4), MineCell.MINE)),
인접한 칸이 연쇄적으로 mine이 아니라면 모두 열려야하는데 그 경우에 대한 테스트도 필요해보이네요.

2024-12-23 15:18 UTC, janghomoon commented on src/main/kotlin/mine/controller/MineController.kt
> +                isRunning = false
수정하고나서 비교해보니  말씀하신 방향이 훨씬 가독성이 훨씬 좋습니다 !

2024-12-24 10:26 UTC, ddaaac requested changes
안녕하세요 장호님 👋 

리뷰 반영 잘 해주셨습니다.
로직이 조금 바뀔 부분이 있는 것 같아서 수정하시고 리뷰요청 부탁드립니다 (_ _)

2024-12-24 10:26 UTC, ddaaac commented on src/test/kotlin/mine/domain/BoardCalculatorTest.kt
> +        val coordinate = Coordinate(1, 1)
<img width="242" alt="image" src="https://github.com/user-attachments/assets/8f1ad5bc-d383-46f5-b165-c7f4bd37e2cc" />

저 빈칸 중 어디를 누르더라도 저 영역이 한 번에 드러나야합니다. 이 테스트를 예시로 들면 0, 0을 열면 저 칸들이 모두 열려야겠죠.
빈 칸 + 지뢰 칸까지 모두 포함해서 테스트가 필요해보여요.

2024-12-24 10:26 UTC, ddaaac commented on src/main/kotlin/mine/controller/MineController.kt
> +            val isAllMinedOpen = mine.isAllMinesOpened()
`마인을 제외한 셀이 모두 열렸다면`이라는 네이밍이 적당해보여요!

2024-12-24 10:26 UTC, ddaaac commented on src/main/kotlin/mine/domain/AdjacentMineRow.kt
> +    ): Int {
kotlin에서 require, check는 예외를 검사할 때 사용되는 메서드들입니다.
메서드 이름을 적당히 수정해보면 좋을 것 같습니다~

2024-12-24 10:26 UTC, ddaaac commented on src/main/kotlin/mine/domain/MineRow.kt
> +    private fun updateCell(
여기 메서드들도 좀 더 구체적으로 하는 일이 드러나면 좋을 것 같아요.
이 메서드들이 하는 행위는 무엇일까요?

2024-12-24 10:26 UTC, ddaaac commented on src/main/kotlin/mine/enums/MineCell.kt
> +    }
```suggestion
    var isOpen: Boolean = false
        protected set
```
조금 더 간단하게 표현할 수 있을 것 같아요.
아니라면 private setter를 사용해도 좋구요.

2024-12-24 13:11 UTC, janghomoon commented
범준님 안녕하세요 이브날에도 빠른 피드백 주셔서 감사합니다 
크리스마스 잘보내세요 ㅎㅎ

2024-12-26 09:25 UTC, ddaaac requested changes
안녕하세요 장호님 👋 

리뷰가 늦어서 죄송합니다!

동작에 대한 코멘트 남겼으니 확인해주세요!

2024-12-26 09:25 UTC, ddaaac commented on src/main/kotlin/mine/controller/MineController.kt
> +                    boardCalculator.openCells(mine.mineBoard, coordinate)
`minesweeper.openCells(coordinate)`와 `boardCalculator.openCells(mine.mineBoard, coordinate)`는 어떤 차이가 있을까요?

2024-12-26 09:25 UTC, ddaaac commented on src/test/kotlin/mine/domain/BoardCalculatorTest.kt
> +        mineBoard[2].mineCells[2].isOpen shouldBe true
c c c
     c c *
     c * c
 
이 모양에서 가운데를 열면 맨 오른쪽 아래는 닫혀있어야하지 않을까요? 지뢰를 넘어서 열면 안 될 것 같아요.
[지뢰 찾기 게임](https://minesweeper.online/ko/)을 한 번 가볍게 해보셔도 좋을 것 같습니다 😄

2024-12-26 09:25 UTC, ddaaac commented on src/main/kotlin/mine/domain/MineRow.kt
> +        val colInRange = colIndex in (coordinate.y - CELL_POSITIVE)..(coordinate.y + CELL_POSITIVE)
로직 가장 깊숙한 곳까지 row, col 파라미터가 넘어오다보니 로직 파악이 쉽게 되지 않는 것 같아요.
row, col에 대한 검사는 각 row, col을 이터레이션 돌 때 할 수 있지 않을까요?

2024-12-26 13:12 UTC, janghomoon commented on src/main/kotlin/mine/controller/MineController.kt
> +                    boardCalculator.openCells(mine.mineBoard, coordinate)
범준님 안녕하세요 
minesweeper.openCells(coordinate) 는 수정되어 없는 부분 같은데 혹시 제가 잘못 알고 있는걸까요  ;;?

2024-12-26 17:17 UTC, janghomoon commented on src/test/kotlin/mine/domain/BoardCalculatorTest.kt
> +        mineBoard[2].mineCells[2].isOpen shouldBe true
범준님 게임하면서 0일때만 인접셀이 열리는거 같군요;;  지웠다 수정했다  했는데  제가 봤을떄는 잘수정한것 같은데 다시 확인해주시면 감사합니다 !

2024-12-26 23:21 UTC, janghomoon commented on src/main/kotlin/mine/domain/MineRow.kt
> +        val colInRange = colIndex in (coordinate.y - CELL_POSITIVE)..(coordinate.y + CELL_POSITIVE)
이게 맞게 수정된건지는 모르겠지만  호출하는 함수쪽으로 이동해서 수정했습니다.   위쪽으로 옮기게되면  반복문 안에 호출되는데 이렇게 되면 맞는걸까요??

2024-12-27 09:06 UTC, ddaaac requested changes
안녕하세요 장호님 👋 

몇 가지 코멘트 남겼으니 확인해주세요~

2024-12-27 09:06 UTC, ddaaac commented on src/main/kotlin/mine/controller/MineController.kt
> +                    boardCalculator.openCells(mine.mineBoard, coordinate)
지금은 minesweeper에서 mineBoard를 "꺼내서" BoardCalculator에 전달하고, 이를 통해 셀들을 열고 있어요.
[값을 꺼내지 말고 객체에 메세지를 던져보면](https://tecoble.techcourse.co.kr/post/2020-04-28-ask-instead-of-getter/) 좋을 것 같아서 남긴 코멘트입니다.
MineSweeper객체는 board에 관련된 정보를 스스로 알고 있고, 그 board를 여는 역할도 수행할 수 있는데 따로 BoardCalculator에서 열어주지 않아도 될 것 같아서요.

2024-12-27 09:06 UTC, ddaaac commented on src/main/kotlin/mine/domain/MineRow.kt
> +        val colInRange = colIndex in (coordinate.y - CELL_POSITIVE)..(coordinate.y + CELL_POSITIVE)
제가 생각했던 방식은 UpdateMineRow를 없애는 방향이긴 했습니다.
```kotlin
            mineBoard.forEachIndexed { rowIndex, row ->
                UpdateMineRow(row = row, coordinate = coordinate, rowIndex = rowIndex).updateCells()
            }
```

여기서 row가 coordinate에 근접해있는 row인지 미리 알 수 있으니 여기서 필터링하면 어떨까 해서 남긴 코멘트에요.

2024-12-27 09:06 UTC, ddaaac commented on src/test/kotlin/mine/domain/BoardCalculatorTest.kt
> +        mineBoard[2].mineCells[2].isOpen shouldBe false
이 전 코멘트에서도 남겼지만 

 c c c
 c c *
 c * c

여기서 1,1을 연다면

 o o o
 o o *
 o * c

처럼 열려야합니다.
로직을 생각해본다면

1. 좌표에 해당하는 칸을 엽니다
2. 좌표의 8방향을 모두 확인해서 지뢰가 아닌 열려있는 칸이 있다면 3으로 넘어갑니다. 아니면 종료합니다.
3. 해당 좌표를 사용해 1로 돌아갑니다.

이렇게 될 것 같아요. 좌표의 8방향만 여는 것이 아니라 이를 반복해야하는 점을 포함해서 구현해주시면 될 것 같습니다!

2024-12-28 03:24 UTC, ddaaac requested changes
안녕하세요 장호님 👋 

코멘트 확인 부탁드립니다!

2024-12-28 03:24 UTC, ddaaac commented on src/test/kotlin/mine/domain/MinesweeperTest.kt
> +    @Test
```kotlin
    @Test
    fun `open cell test`() {
        val tempBoard =
            listOf(
                MineRow(listOf(MineCell.initial(), MineCell.initial(), MineCell.initial(), MineCell.initial(), MineCell.initial())),
                MineRow(listOf(MineCell.initial(), MineCell.initial(), MineCell.initial(), MineCell.initial(), MineCell.MINE)),
                MineRow(listOf(MineCell.initial(), MineCell.initial(), MineCell.initial(), MineCell.MINE, MineCell.initial())),
                MineRow(listOf(MineCell.initial(), MineCell.initial(), MineCell.MINE, MineCell.initial(), MineCell.initial())),
                MineRow(listOf(MineCell.initial(), MineCell.MINE, MineCell.initial(), MineCell.initial(), MineCell.initial())),
            )
        val minesweeper =
            Minesweeper(
                height = 5,
                width = 5,
                mineCount = 4,
                mineBoard = tempBoard,
            )

        val coordinate = Coordinate(1, 1)

        minesweeper.openCells(coordinate)

        val resultMineBoard = minesweeper.mineBoard

        (1..5).forEach { row ->
            (1..(6 - row)).forEach { col ->
                resultMineBoard[row - 1].mineCells[col - 1].isOpen shouldBe true
            }
            ((8 - row)..5).forEach { col ->
                resultMineBoard[row - 1].mineCells[col - 1].isOpen shouldBe false

            }
        }
    }
```

테스트를 대략적으로 짜긴 했는데 이 테스트가 통과하도록 로직을 구현해주시면 좋을 것 같습니다. 주변 셀들을 계속 탐색해야해요.

2024-12-28 09:03 UTC, janghomoon commented
범준님 안녕하세요 게임 구현이 자꾸 잘못되어서 죄송합니다;; 
이번에 다시 수정 해서 올렸는데 번거롭지만 다시확인 부탁드립니다.

2024-12-29 03:36 UTC, ddaaac approved these changes
안녕하세요 장호님 👋 

리뷰 반영 잘 해주셨습니다.

다음 단계 진행해주세요!

2024-12-29 03:36 UTC, ddaaac commented on src/main/kotlin/mine/domain/Minesweeper.kt
> +            if (isOpenedCellOrVisitedCell(currentCell, x, y, visited)) continue
넘어가는 파라미터가 많은 것 같아요.
isOpenedCell(cell) || isVisitedCell(coordinate, visited) 처럼 만들 수 있을 것 같아요.
파라미터 숫자도 생각해주세요!

2024-12-29 03:36 UTC, ddaaac commented on src/test/kotlin/mine/domain/MinesweeperTest.kt
> +    @Test
잘 변경해주셨네요!
미리 테스트를 만들어놓고 그 테스트를 통과시키기 위해서 코드를 짜면 코드 짜는 게 훨씬 수월하다고 느껴지는 것 같습니다. 일단 짜놓고 테스트를 돌려서 통과하기만 하면 되니깐요.

그래서 다음 단계를 진행할 떄는 아예 처음부터  TDD로 구현해보시는 걸 추천드립니다. 새로 구현하다보면 느끼는 점이 많을 것 같아요~

2024-12-29 03:36 UTC, merged