[step4] 지뢰 찾기(리팩터링)
next-step/kotlin-minesweeper pull request #52
Opened 2021-03-30 09:20 UTC by karian7

안녕하세요! 선호님. 드디어 마지막 단계네요.

[지난PR](https://github.com/next-step/kotlin-minesweeper/pull/42) 에서 피드백 주신내용과 추가로 클래스 리네임을 적용하였습니다.
state 패턴으로 바꾸는 부분은 현재 구조상 `Cell` 자체를 바꿀 수 없다고 판단되어 `CellState` 라는 상태를 추가하였어요.
`Cell` 자체를 상태로 표현하려면 `Board` 객체가 `cells`

2021-03-31 10:14 UTC, vsh123 requested changes
광수님 안녕하세요!!
마지막 단계까지 수고하셨습니다 :)

크게 코멘트할 부분이 있지는 않았던 것 같아요!
몇가지 의견을 남겼으니 한번 확인 부탁드릴게요~~ :)

2021-03-31 10:14 UTC, vsh123 commented on src/main/kotlin/minesweeper/domain/Cell.kt
> +        val oldState = cellState
해당 함수에 대한 방어처리가 함께들어가면 좋을 것 같아요~!!
Operation.Smart가 아닌 다른 클래스에서 해당 함수를 검증없이 호출했을 때는, Open된 Cell이 다시한번 Open도 가능할 것으로 보여요

2021-03-31 11:24 UTC, karian7 commented on src/main/kotlin/minesweeper/domain/CellFactory.kt
> +            protoCells.increaseCount()
생각해보니 `updateSide` `increaseCount` 가 공개될필요가 없네요.
`cells()` 내부로 옮겼습니다. 😀 5a456b060aa6b28cdc3beed88872df7deeeaadc3

2021-03-31 11:35 UTC, karian7 commented on src/main/kotlin/minesweeper/domain/Cell.kt
> +        val oldState = cellState
open 된 셀이 다시 open 하면 한번 더 상개타 감싸지긴 하지만 예외상황이 발생하진 않긴해요. 그래도 보완해 두었습니다. 😀 75f0f59bef5605a7b1ac1208ea6fb7351febb7ab

2021-03-31 11:50 UTC, karian7 commented on src/main/kotlin/minesweeper/domain/Operation.kt
> +    class Smart(private val board: Board, private val matrix: Matrix) : Operation {
현재 설계는 뭔가를 만들고 새로운 객체를 생성하는 빌더와 엔티티를 수정하는 조정자를 분리하기 위해 `Operation` 객체를 추가하게 되었습니다. 그리고 리펙토링 이전에는 `Board` 가 `Cells` 라는 일급컬랙션이었는데요, 지금은 많이 변해서 `Operation` 이 필요없다고 판단되네요. 078519fbdf2a2bdc52332f8d2287df53bac7d77a

2021-04-01 13:59 UTC, vsh123 approved these changes
광수님 안녕하세요!
지뢰찾기 미션을 보면서 제가 배운 점이 더 많은 것 같네요 ㅎㅎ

이번 미션은 마무리하도록 하겠습니다!!
코틀린과정 모두 수행하시느라 수고하셨습니다!! :)

2021-04-01 14:00 UTC, merged